import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from '../src/engine.js';
import {campAction,ensureCamp} from '../src/camp-game.js';
import {campAt,placementError,passable} from '../src/camp-data.js';
import {campRooms,coverAt,campBed} from '../src/camp-rooms.js';
import {strokeTiles,batchPlan} from '../src/camp-plans.js';
import {sleepPlace} from '../src/sleep-data.js';
import {sleep,sleepPreview} from '../src/sleep.js';
import {GameStore} from '../src/store.js';
import {roomPanel,demolitionPanel} from '../src/camp-room-view.js';
function game(){const s=E.newGame(E.demoWorld(),{mode:'demo',seed:'room-tests'});E.cell(s).camp={level:1,storage:{},facilities:{bed:true}};campAction(s,'campEnter');s.campMode='simple';return s;}
function room({roof=true,door=true}={}){const s=game(),l=campAt(s).layout;l.serial=100;for(let y=2;y<=6;y++)for(let x=2;x<=6;x++){if(x===2||x===6||y===2||y===6){const type=x===4&&y===6?'door':'wall';l.objects.push({id:`r-${x}-${y}`,type,x,y,rot:0,name:type,...(type==='door'?{open:!door}:{})});}else if(roof)l.objects.push({id:`roof-${x}-${y}`,type:'roof',x,y,rot:0,name:'屋顶'});}E.validateSave(s);return s;}
const complete=s=>campRooms(campAt(s).layout).regions.filter(r=>r.complete).length;
test('closed walls plus complete roof define a room, doors and roof holes update immediately',()=>{const s=room(),l=campAt(s).layout;assert.equal(complete(s),1);assert.equal(sleepPlace(s),'shelter');const d=l.objects.find(o=>o.type==='door');campAction(s,'campDoor',{id:d.id});assert.equal(complete(s),0);assert.equal(sleepPlace(s),'covered');campAction(s,'campDoor',{id:d.id});l.objects=l.objects.filter(o=>o.id!=='roof-5-5');assert.equal(complete(s),0);assert.equal(sleepPlace(s),'covered');assert(roomPanel(s).includes('5,5'));l.objects=l.objects.filter(o=>o.id!=='roof-3-3');assert.equal(sleepPlace(s),'outdoor');});
test('map edge and furniture do not seal rooms, bare enclosed yards are exposed',()=>{const s=room({roof:false});assert.equal(complete(s),0);assert.equal(sleepPlace(s),'outdoor');const plain=game(),l=campAt(plain).layout;l.objects.push({id:'roof',type:'roof',x:1,y:1,rot:0,name:'顶'});assert.equal(coverAt(l,[{x:1,y:1}]).kind,'covered');assert.equal(campRooms(l).regions.filter(r=>r.closed).length,0);});
test('roofs share cells with floors and beds but never block walking',()=>{const s=game();s.bag.wood=20;campAction(s,'campPlace',{type:'roof',x:7,y:12,rot:0});campAction(s,'campPlace',{type:'floor',x:7,y:12,rot:0});assert(passable(campAt(s).layout,7,12));campAction(s,'campPlace',{type:'roof',x:3,y:3,rot:0});assert(!passable(campAt(s).layout,3,3));E.validateSave(s);});
test('batch costs charge only missing tiles and overlapping or blocked plans do not debit',()=>{const s=game();s.bag.wood=20;const points=strokeTiles({x:8,y:9},{x:9,y:10},'rect'),t=s.time;const p=batchPlan(s,'floor',points);assert.equal(p.minutes,20);assert.equal(p.cost.wood,4);campAction(s,'campBatchPlace',{type:'floor',points});assert.equal(s.time,t+20);assert.equal(s.bag.wood,16);const again=batchPlan(s,'floor',points);assert.equal(again.objects.length,0);assert.equal(again.skipped,4);const before=E.clone(s);assert.throws(()=>campAction(s,'campBatchPlace',{type:'wall',points:[{x:8,y:9},{x:5,y:12}]}));assert.deepEqual(s,before);E.validateSave(s);});
test('straight strokes snap to one axis, duplicate coordinates cannot double-charge',()=>{assert.deepEqual(strokeTiles({x:2,y:8},{x:5,y:9},'line'),[{x:2,y:8},{x:3,y:8},{x:4,y:8},{x:5,y:8}]);const s=game();assert.equal(batchPlan(s,'roof',[{x:8,y:8},{x:8,y:8}]).objects.length,1);assert.throws(()=>batchPlan(s,'bed',[{x:8,y:8}]));assert.throws(()=>strokeTiles({x:0,y:8},{x:5,y:8}));});
test('covered beds avoid rain penalties and complete rooms improve actual sleep',()=>{const exposed=room({roof:false}),indoor=room(),covered=room({door:false});for(const s of [exposed,indoor,covered]){s.stats.stamina=0;s.stats.health=40;s.stats.spirit=20;s.stats.food=s.stats.water=100;for(let t=240;t<4000;t+=240){s.time=t;E.tick(s,1,0);if(s.weather==='小雨')break;}}const a=sleepPreview(exposed,'2h'),b=sleepPreview(indoor,'2h'),c=sleepPreview(covered,'2h');assert.equal(a.rainMinutes,120);assert.equal(b.rainMinutes,0);assert.equal(c.rainMinutes,0);assert(b.after.stamina>c.after.stamina&&c.after.stamina>a.after.stamina);const r=sleep(indoor,'2h');assert.deepEqual(r.after,b.after);assert.equal(r.place,'shelter');});
test('selected bed determines simple sleep instead of silently using another room',()=>{const s=room();campAt(s).layout.objects.push({id:'outside-bed',type:'bed',x:10,y:10,rot:0,name:'露天床'});campAction(s,'campSelectBed',{id:'outside-bed'});assert.equal(campBed(s).bed.id,'outside-bed');assert.equal(sleepPlace(s),'outdoor');campAction(s,'campSelectBed',{id:'old-bed'});assert.equal(sleepPlace(s),'shelter');E.validateSave(s);});
test('demolition preview is read-only and explains lost room protection',()=>{const s=room(),before=E.clone(s),html=demolitionPanel(s,'roof-5-5');assert(html.includes('1 → 0'));assert(html.includes('确认拆除'));assert.deepEqual(s,before);campAction(s,'campRemove',{id:'roof-5-5'});assert.equal(complete(s),0);E.validateSave(s);});
test('batch save failure restores all materials, time and layout',async()=>{const mem=new Map(),storage={getItem:k=>mem.get(k)??null,setItem:(k,v)=>mem.set(k,v)},store=new GameStore(storage,'room-rollback');store.switch('a');await store.run(()=>game(),{create:true});await store.run(s=>{s.bag.wood=20;});const before=E.clone(store.state);storage.setItem=()=>{throw Error('disk');};await assert.rejects(store.run(s=>{campAction(s,'campBatchPlace',{type:'roof',points:[{x:8,y:8},{x:9,y:8}]});}),/disk/);assert.deepEqual(store.state,before);});
test('saved rooms are re-derived and old layouts remain valid without free roofs',()=>{const s=room();assert.equal(complete(E.validateSave(E.clone(s))),1);const old=game();assert(!campAt(old).layout.objects.some(o=>o.type==='roof'));assert.equal(sleepPlace(old),'outdoor');E.validateSave(old);const bad=E.clone(s);bad.player.camp.bedId='missing';assert.throws(()=>E.validateSave(bad),/床铺/);});
