import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from '../src/engine.js';
import {campAction as act,ensureCamp,campBag} from '../src/camp-game.js';
import {campAt,placementError,campPath,CAMP_EXIT,nearCampFacility} from '../src/camp-data.js';
import {gainFood,foodBatches} from '../src/provisions.js';
import {GameStore} from '../src/store.js';
import {sleepPlace} from '../src/sleep-data.js';
import {hasFacility} from '../src/shelter-data.js';
import {campInterior} from '../src/camp-map-view.js';
const game=()=>{const s=E.newGame(E.demoWorld(),{mode:'demo'});E.cell(s).camp={level:1,storage:{},facilities:{bed:true,cellar:true,stove:true}};return s;};
const enter=()=>{const s=game();act(s,'campEnter');return s;};
test('migration retains food age and existing facilities, persists idempotently',()=>{const s=game(),c=campAt(s);gainFood(s,c.storage,'rawmeat',2,600);E.tick(s,60,0);const life=foodBatches(s,c.storage)[0].life;ensureCamp(s);assert.equal(foodBatches(s,c.storage)[0].life,life);assert.equal(c.provisions.rate,1);assert.equal(c.layout.objects.length,4);const before=E.clone(c.layout);ensureCamp(s);assert.deepEqual(c.layout,before);E.validateSave(s);});
test('camp movement is free and map exit requires entrance',()=>{const s=enter(),t=s.time;act(s,'campMove',{x:7,y:12});assert.equal(s.time,t);assert.throws(()=>act(s,'campExit'),/入口/);act(s,'campMove',{x:7,y:14});act(s,'campExit');assert(!s.player.camp);E.validateSave(s);});
test('placement consumes resources once, rotation and collision are enforced',()=>{const s=enter();s.bag.wood=10;s.bag.cloth=3;act(s,'campMove',{x:7,y:12});const t=s.time;act(s,'campPlace',{type:'bed',x:8,y:11,rot:1});assert.equal(s.bag.wood,7);assert.equal(s.bag.cloth,0);assert.equal(s.time,t+60);const before=E.clone(s);assert.throws(()=>act(s,'campPlace',{type:'box',x:8,y:11,rot:0}),/重叠/);assert.deepEqual(s,before);E.validateSave(s);});
test('build validation rejects entrance blockage and player overlap',()=>{const s=enter(),l=campAt(s).layout;assert(placementError(l,{type:'wall',x:7,y:13,rot:0},s.player.camp));assert(placementError(l,{type:'box',x:7,y:14,rot:0},s.player.camp));assert.equal(campPath(l,CAMP_EXIT,{x:5,y:12}),null);});
test('independent boxes preserve quantities and freshness; full boxes cannot be moved or dismantled',()=>{const s=enter();s.bag.wood=6;act(s,'campMove',{x:7,y:12});act(s,'campPlace',{type:'box',x:8,y:12,rot:0});const o=campAt(s).layout.objects.at(-1);gainFood(s,s.bag,'rawmeat',2,400);act(s,'campDeposit',{id:o.id,item:'rawmeat'});assert.equal(o.items.rawmeat,1);assert.equal(s.bag.rawmeat,1);assert.equal(foodBatches(s,o.items)[0].life,400);assert.throws(()=>act(s,'campRemove',{id:o.id}),/清空/);assert.throws(()=>act(s,'campRelocate',{id:o.id,x:9,y:12,rot:0}),/清空/);act(s,'campWithdraw',{id:o.id,item:'rawmeat'});act(s,'campRename',{id:o.id,name:'食物箱'});assert.equal(o.name,'食物箱');act(s,'campRelocate',{id:o.id,x:8,y:11,rot:0});E.validateSave(s);});
test('legacy box requires proximity, existing regional storage shortcut is blocked',()=>{const s=enter();s.bag.wood=1;assert.throws(()=>act(s,'campDeposit',{id:'legacy',item:'wood'}),/旁边/);assert.throws(()=>E.campTransfer(s,'wood',true),/储物箱/);s.player.camp={x:6,y:12};act(s,'campDeposit',{id:'legacy',item:'wood'});assert.equal(campAt(s).storage.wood,1);E.validateSave(s);});
test('beds and work facilities require local proximity; cellar preservation is per container',()=>{const s=enter(),c=campAt(s),cellar=c.layout.objects.find(o=>o.type==='cellar');assert.equal(sleepPlace(s),'outdoor');assert.equal(hasFacility(s,'bed'),false);s.player.camp={x:4,y:3};assert(nearCampFacility(s,'bed'));assert.equal(sleepPlace(s),'shelter');gainFood(s,cellar.items,'rawmeat',1,500);gainFood(s,c.storage,'rawmeat',1,500);E.tick(s,60,0);assert.equal(foodBatches(s,cellar.items)[0].life,485);assert.equal(foodBatches(s,c.storage)[0].life,440);E.validateSave(s);});
test('forged layout inventories, overlap, unsafe ids and player positions are rejected',()=>{const s=enter();for(const mutate of [x=>campAt(x).layout.objects[0].id='bad"id',x=>campAt(x).layout.objects.push({...campAt(x).layout.objects[0],id:'copy'}),x=>x.player.camp={x:5,y:12},x=>campAt(x).layout.objects.find(o=>o.type==='cellar').items.bad=1]){const bad=E.clone(s);mutate(bad);assert.throws(()=>E.validateSave(bad));}});
test('failed camp placement commit rolls back inventory and layout',async()=>{const mem=new Map(),storage={getItem:k=>mem.get(k)??null,setItem:(k,v)=>mem.set(k,v)},store=new GameStore(storage,'camp-test');store.switch('a');await store.run(()=>enter(),{create:true});await store.run(s=>{s.bag.wood=10;s.player.camp={x:7,y:12};});const before=E.clone(store.state);storage.setItem=()=>{throw Error('disk');};await assert.rejects(store.run(s=>{act(s,'campPlace',{type:'box',x:8,y:12,rot:0});}),/disk/);assert.deepEqual(store.state,before);});
test('SVG map renders furniture safely with action and building controls',()=>{const s=enter();campAt(s).layout.objects[0].name='<unsafe>';const html=campInterior(s,{mode:'walk',type:'box',rot:0,id:'legacy',tile:null,zoom:1});assert(html.includes('<svg'));assert(html.includes('data-camp-tile'));assert(html.includes('&lt;unsafe&gt;'));assert(!html.includes('<unsafe>'));});

test('doors block paths until opened but camp movement is unrestricted by night',()=>{const s=enter();s.bag.wood=4;s.bag.scrap=1;act(s,'campMove',{x:7,y:12});act(s,'campPlace',{type:'door',x:8,y:12,rot:0});const o=campAt(s).layout.objects.at(-1);assert.equal(campPath(campAt(s).layout,s.player.camp,{x:8,y:12}),null);act(s,'campDoor',{id:o.id});act(s,'campMove',{x:8,y:12});assert.throws(()=>act(s,'campDoor',{id:o.id}),/离开门/);s.time=1200;act(s,'campMove',{x:8,y:7});assert.deepEqual(s.player.camp,{x:8,y:7});assert(campAt(s).layout.seen['7,12']);E.validateSave(s);});
test('leaving and re-entering retains layout and a freshly named box',()=>{const s=enter();s.bag.wood=3;act(s,'campMove',{x:7,y:12});act(s,'campPlace',{type:'box',x:8,y:12,rot:0});const o=campAt(s).layout.objects.at(-1);act(s,'campRename',{id:o.id,name:'工具箱'});const layout=()=>campAt(s).layout.objects.map(({provisions,...o})=>o),before=E.clone(layout());act(s,'campMove',CAMP_EXIT);act(s,'campExit');act(s,'campEnter');assert.deepEqual(layout(),before);E.validateSave(E.clone(s));});

test('free camp travel and transfers preserve survival values, fuel and food age',()=>{const s=enter();s.bag.torch=1;s.lighting={active:'torch',torch:60,flashlight:0,facing:'north'};gainFood(s,s.bag,'rawmeat',1,200);s.injuries={trauma:40,bleeding:1,infection:1,exposure:50};const t=s.time,stats=E.clone(s.stats),w=E.clone(s.injuries);act(s,'campMove',{x:6,y:12});act(s,'campDeposit',{id:'legacy',item:'rawmeat'});act(s,'campWithdraw',{id:'legacy',item:'rawmeat'});assert.equal(s.time,t);assert.deepEqual(s.stats,stats);assert.deepEqual(s.injuries,w);assert.equal(s.lighting.torch,60);assert.equal(foodBatches(s).find(b=>b.id==='rawmeat').life,200);E.validateSave(s);});
test('simple mode uses the same distant containers and facilities without moving player',()=>{const s=enter(),pos=E.clone(s.player.camp),t=s.time;s.bag.wood=1;assert.throws(()=>act(s,'campDeposit',{id:'legacy',item:'wood'}));act(s,'campSetMode',{mode:'simple'});act(s,'campDeposit',{id:'legacy',item:'wood'});assert.equal(campAt(s).storage.wood,1);assert(hasFacility(s,'bed'));assert.equal(sleepPlace(s),'shelter');assert.deepEqual(s.player.camp,pos);assert.equal(s.time,t);act(s,'campSetMode',{mode:'map'});assert(!hasFacility(s,'bed'));assert.throws(()=>act(s,'campWithdraw',{id:'legacy',item:'wood'}));E.validateSave(s);});
test('simple construction places real furniture at valid positions and charges normal costs',()=>{const s=enter();s.bag.wood=6;act(s,'campSetMode',{mode:'simple'});const t=s.time,n=campAt(s).layout.objects.length;act(s,'campAutoPlace',{type:'box'});act(s,'campAutoPlace',{type:'box'});const objects=campAt(s).layout.objects;assert.equal(objects.length,n+2);assert.equal(s.bag.wood,0);assert.equal(s.time,t+40);assert.notDeepEqual([objects.at(-1).x,objects.at(-1).y],[objects.at(-2).x,objects.at(-2).y]);E.validateSave(s);const before=E.clone(s);assert.throws(()=>act(s,'campAutoPlace',{type:'box'}),/材料/);assert.deepEqual(s,before);});
test('mode survives save reload and simple exit is free without changing the map',async()=>{const mem=new Map(),storage={getItem:k=>mem.get(k)??null,setItem:(k,v)=>mem.set(k,v)},store=new GameStore(storage,'camp-modes');store.switch('a');await store.run(()=>enter(),{create:true});await store.run(s=>{act(s,'campSetMode',{mode:'simple'});s.player.camp={x:7,y:10};});store.switch('b');assert.equal(store.state,null);store.switch('a');assert.equal(store.state.campMode,'simple');const t=store.state.time,layout=E.clone(campAt(store.state).layout);await store.run(s=>{act(s,'campExit');});assert.equal(store.state.time,t);assert.deepEqual(campAt(store.state).layout,layout);assert(!store.state.player.camp);const bad=E.clone(store.state);bad.campMode='bad';assert.throws(()=>E.validateSave(bad),/模式/);});

test('map mode allows remote placement and relocation outside night vision without moving player',()=>{const s=enter();s.time=1200;s.bag.wood=6;const pos=E.clone(s.player.camp),t=s.time;act(s,'campPlace',{type:'box',x:1,y:1,rot:0});const o=campAt(s).layout.objects.at(-1);act(s,'campRelocate',{id:o.id,x:12,y:2,rot:1});assert.deepEqual(s.player.camp,pos);assert.equal(s.bag.wood,3);assert.equal(s.time,t+30);assert.deepEqual([o.x,o.y,o.rot],[12,2,1]);assert.throws(()=>act(s,'campDeposit',{id:o.id,item:'wood'}),/旁边/);E.validateSave(s);});
test('remote layout edits retain collision, entrance and nonempty-container checks',()=>{const s=enter();s.bag.wood=3;act(s,'campPlace',{type:'box',x:1,y:1,rot:0});const o=campAt(s).layout.objects.at(-1);const before=E.clone(s);for(const [x,y]of [[5,12],[7,13],[15,1]])assert.throws(()=>act(s,'campRelocate',{id:o.id,x,y,rot:0}));assert.deepEqual(s,before);gainFood(s,o.items,'rawmeat',1);assert.throws(()=>act(s,'campRelocate',{id:o.id,x:12,y:2,rot:0}),/清空/);E.validateSave(s);});
test('remote furniture move button and legal preview remain enabled outside sight',()=>{const s=enter();s.time=1200;const html=campInterior(s,{mode:'walk',type:'bed',rot:0,id:'old-bed',tile:null,zoom:1});assert.match(html,/data-action="campMoveFurniture"[^>]*>搬动/);assert(!html.match(/data-action="campMoveFurniture"[^>]*disabled/));const preview=campInterior(s,{mode:'build',type:'bed',rot:1,id:'old-bed',moving:'old-bed',tile:{x:10,y:11},zoom:1});assert(!preview.match(/data-action="campConfirm"[^>]*disabled/));assert(preview.includes('不扣材料'));});

test('camp map stays fully visible at night and behind walls without lighting',()=>{const s=enter();s.bag.wood=2;act(s,'campPlace',{type:'wall',x:7,y:12,rot:0});const view={mode:'walk',type:'box',rot:0,id:null,tile:null,zoom:1};const day=campInterior(s,view);s.time=1200;assert.equal(campInterior(s,view),day);act(s,'campMove',{x:7,y:2});assert.deepEqual(s.player.camp,{x:7,y:2});assert.equal(Object.keys(campAt(s).layout.seen).length,225);assert.equal(campPath(campAt(s).layout,s.player.camp,{x:7,y:12}),null);assert.throws(()=>act(s,'campMove',{x:15,y:2}),/范围/);E.validateSave(s);});
