import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from '../src/engine.js';
import {grantBenefit,activeBenefits,benefitsPanel} from '../src/positive-states.js';
import {sleep,sleepPreview} from '../src/sleep.js';
import {gainFood} from '../src/provisions.js';
import {conditionSummary,injuryPanel} from '../src/survival-view.js';
const game=()=>E.newGame(E.demoWorld(),{mode:'demo',seed:'benefits'});
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
test('cooked meal grants satisfaction only crossing fullness threshold; overeating does not refresh',()=>{const s=game();s.stats.food=55;gainFood(s,s.bag,'cookedmeat',3);E.useItem(s,'cookedmeat');assert.equal(s.benefits.satisfied,s.time+240);const end=s.benefits.satisfied;E.tick(s,10,0);E.useItem(s,'cookedmeat');assert.equal(s.benefits.satisfied,end);const t=game();t.stats.food=55;E.useItem(t,'food');assert.equal(t.benefits,undefined);});
test('rest bonus applies only to active minutes and spirit gain stops at expiration',()=>{const s=game(),t=E.clone(s);s.stats.stamina=t.stats.stamina=10;s.stats.spirit=t.stats.spirit=40;s.benefits={satisfied:s.time+30};E.rest(s);E.rest(t);near(s.stats.stamina-t.stats.stamina,1.125);near(s.stats.spirit-t.stats.spirit,.5);assert.equal(activeBenefits(s).length,0);});
test('rested reduces only basic effort during overlap, preserving injury penalty',()=>{const s=game(),t=E.clone(s);s.benefits={rested:s.time+20};E.tick(s,60);E.tick(t,60);near(s.stats.stamina-t.stats.stamina,.18);assert.equal(activeBenefits(s).length,0);});
test('sleep preview matches recovery and earned benefit without mutating source',()=>{const s=game();E.cell(s).camp={level:1,storage:{}};s.stats.stamina=10;grantBenefit(s,'satisfied');const before=E.clone(s),p=sleepPreview(s,'8h');assert.deepEqual(s,before);assert.equal(p.gainedRested,true);const r=sleep(s,'8h');assert.deepEqual(r.after,p.after);assert.equal(s.benefits.rested,s.time+360);assert.equal(s.benefits.satisfied,undefined);const short=game();E.cell(short).camp={level:1,storage:{}};sleep(short,'2h');assert.equal(short.benefits,undefined);const exposed=game();sleep(exposed,'8h');assert.equal(exposed.benefits,undefined);});
test('needs-interrupted sleep does not earn rested; existing illness is not cured',()=>{const s=game();E.cell(s).camp={level:1,storage:{}};s.stats.water=6;assert.equal(sleep(s,'8h').gainedRested,false);const t=game();E.cell(t).camp={level:1,storage:{}};t.injuries={trauma:10,bleeding:0,infection:1,exposure:0};assert.equal(sleep(t,'8h').gainedRested,false);assert.equal(t.injuries.infection,1);});
test('save validation, context and UI preserve bounded benefits; old saves remain valid',()=>{const s=game();E.validateSave(s);grantBenefit(s,'satisfied');grantBenefit(s,'rested');const copy=E.validateSave(JSON.parse(JSON.stringify(s)));assert.deepEqual(copy.benefits,s.benefits);assert.equal(JSON.parse(E.knownContext(s)).positiveStates.length,2);assert.match(conditionSummary(s),/饱腹满足/);assert.match(injuryPanel(s),/充分休息/);assert.match(benefitsPanel(s),/不叠加/);for(const bad of [{rested:s.time+361},{fake:s.time+1},[],{satisfied:Infinity}]){const t=E.clone(s);t.benefits=bad;assert.throws(()=>E.validateSave(t),/正面状态/);}});

test('zero-time and developer frozen actions neither age benefits nor grant passive spirit',()=>{const s=game();grantBenefit(s,'satisfied');s.stats.spirit=30;const end=s.benefits.satisfied;E.tick(s,0,0);assert.equal(s.stats.spirit,30);s.developer={enabled:true,timeLocked:true,locks:{}};const time=s.time;E.tick(s,600);assert.equal(s.time,time);assert.equal(s.benefits.satisfied,end);assert.equal(s.stats.spirit,30);});
