import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from '../src/engine.js';
import {campAction} from '../src/camp-game.js';
import {campAt,campPath} from '../src/camp-data.js';
import {workshopAction as act} from '../src/workshop.js';
import {outdoorTemperature,thermalSnapshot,roomTemperature,advanceTemperature,heaterFuel,thermalRecovery} from '../src/temperature.js';
import {waterWeather} from '../src/water-data.js';
import {benchLevel} from '../src/workshop-data.js';
import {temperaturePanel,furnitureFunctionPanel} from '../src/workshop-view.js';
import {sleep,sleepPreview} from '../src/sleep.js';
import {GameStore} from '../src/store.js';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
const game=()=>E.newGame(E.demoWorld(),{mode:'demo',seed:'temperature'});
const camp=()=>{const s=game();E.cell(s).camp={level:1,storage:{},facilities:{bench:true,bed:true}};campAction(s,'campEnter');Object.assign(campAt(s).layout.objects.find(o=>o.type==='bench'),{x:9,y:10});s.campMode='simple';return s;};
function room(s){const l=campAt(s).layout;for(let y=2;y<=6;y++)for(let x=2;x<=6;x++){const edge=x===2||y===2||x===6||y===6;if(edge)l.objects.push({id:`wall-${x}-${y}`,type:x===4&&y===6?'door':'wall',x,y,rot:0,name:'墙门',...(x===4&&y===6?{open:false}:{})});else l.objects.push({id:`roof-${x}-${y}`,type:'roof',x,y,rot:0,name:'屋顶'});}l.objects.push({id:'heat',type:'heater',x:5,y:4,rot:0,name:'暖炉'});return l.objects.at(-1);}
test('temperature responds to climate, day, season and rain; old saves default safely',()=>{const s=game(),base=outdoorTemperature(s,900);s.world.environment={climate:'寒冷'};assert(outdoorTemperature(s,900)<base-15);assert.notEqual(outdoorTemperature(s,900),outdoorTemperature(s,180));assert.notEqual(outdoorTemperature(s,900),outdoorTemperature(s,900+7*1440));const old=game();E.validateSave(old);assert.match(temperaturePanel(old),/温度/);E.tick(old,1);assert(old.thermal);E.validateSave(old);});
test('rain wets outdoor player, roof shelters, heat dries and coat mitigates cold',()=>{const s=game();let t=0;while(waterWeather(s,t)!=='小雨')t+=240;s.time=t;s.world.environment={climate:'寒冷'};const coated=E.clone(s);coated.bag.warmcoat=1;act(coated,'wearCoat');E.tick(s,60,0);E.tick(coated,60,0);assert(s.thermal.wet>30);assert(coated.thermal.cold<s.thermal.cold);const sheltered=camp();room(sheltered);sheltered.time=t;E.tick(sheltered,30,0);assert.equal(sheltered.thermal.wet,0);});
test('heater uses finite fuel, warms complete room, door and size reduce benefit',()=>{const s=camp(),h=room(s);s.bag.fuel=1;act(s,'heaterFeed',{id:h.id});act(s,'heaterToggle',{id:h.id});const initial=thermalSnapshot(s).temperature;E.tick(s,30,0);assert.equal(heaterFuel(h,s.time),30);assert(thermalSnapshot(s).temperature>outdoorTemperature(s)+5);const closed=thermalSnapshot(s).temperature;campAt(s).layout.objects.find(o=>o.type==='door').open=true;assert(thermalSnapshot(s).temperature<closed);E.tick(s,60,0);assert.equal(heaterFuel(h,s.time),0);assert.equal(h.heater.lit,false);assert(h.heater.heat<6);E.validateSave(s);});
test('batched and minute-wise thermal simulation agree, while frozen and free actions do nothing',()=>{const s=camp(),h=room(s);s.bag.fuel=1;act(s,'heaterFeed',{id:h.id});act(s,'heaterToggle',{id:h.id});s.thermal={wet:50,cold:30,heat:0,coat:false};const t=E.clone(s);E.tick(s,90,0);for(let i=0;i<90;i++)E.tick(t,1,0);for(const k of ['wet','cold','heat'])near(s.thermal[k],t.thermal[k]);near(h.heater.heat,campAt(t).layout.objects.at(-1).heater.heat);const old=E.clone(s);s.developer={enabled:true,timeLocked:true,locks:{}};E.tick(s,100);assert.deepEqual(s.thermal,old.thermal);assert.deepEqual(h.heater,old.world.cells[`${s.player.x},${s.player.y}`].camp.layout.objects.at(-1).heater);});
test('sleep preview includes heater expiry and applies cold recovery without mutating live game',()=>{const s=camp(),h=room(s);s.bag.fuel=1;act(s,'heaterFeed',{id:h.id});act(s,'heaterToggle',{id:h.id});s.thermal={wet:30,cold:50,heat:0,coat:false};s.stats.stamina=10;assert(thermalRecovery(s)<1);const before=E.clone(s),p=sleepPreview(s,'2h');assert.deepEqual(s,before);assert(p.warnings.some(w=>w.includes('暖炉')));const r=sleep(s,'2h');assert.deepEqual(r.after,p.after);E.validateSave(s);});
test('workshop levels unlock material processing, furniture and guarded upgrades',()=>{const s=camp(),l=campAt(s).layout,b=l.objects.find(o=>o.type==='bench');assert.equal(benchLevel(b),1);s.bag={scrap:2};act(s,'workshopCraft',{recipe:'components'});assert.equal(s.bag.components,3);assert.equal(s.bag.scrap,1);assert.throws(()=>act(s,'workshopCraft',{recipe:'parts'}),/金属工作台/);s.bag={wood:4,components:4,scrap:2};campAction(s,'campPlace',{type:'metalbench',x:8,y:8,rot:0});s.bag={scrap:1,components:2};act(s,'workshopCraft',{recipe:'parts'});assert.equal(s.bag.parts,1);s.bag={wood:4,components:6,parts:2};act(s,'upgradeBench',{id:b.id,level:2});assert.equal(benchLevel(b),2);s.bag={scrap:1,components:3,parts:1};act(s,'workshopCraft',{recipe:'electronics'});assert.equal(s.bag.electronics,1);assert.throws(()=>campAction(s,'campPlace',{type:'radio',x:8,y:9,rot:0}),/3 级/);assert.match(furnitureFunctionPanel(s,b),/2 \/ 3/);E.validateSave(s);});
test('wearing coat prevents last-item storage; leisure shares cooldown and does not reveal clues',()=>{const s=camp(),l=campAt(s).layout;s.bag={warmcoat:1};act(s,'wearCoat');assert.throws(()=>campAction(s,'campDeposit',{id:'legacy',item:'warmcoat'}),/脱下/);act(s,'wearCoat');campAction(s,'campDeposit',{id:'legacy',item:'warmcoat'});l.objects.push({id:'chair',type:'chair',x:8,y:8,rot:0,name:'椅子'},{id:'radio',type:'radio',x:9,y:8,rot:0,name:'广播'});s.stats.spirit=40;const clues=E.clone(s.clues);act(s,'relaxFurniture',{id:'chair'});assert(s.stats.spirit>40);s.bag.battery=1;assert.throws(()=>act(s,'relaxFurniture',{id:'radio'}),/稍后/);assert.equal(s.bag.battery,1);assert.deepEqual(s.clues,clues);E.validateSave(s);});
test('malformed temperature and furnace saves fail; failed upgrade persistence rolls back costs',async()=>{const s=camp(),b=campAt(s).layout.objects.find(o=>o.type==='bench');s.bag={wood:4,components:6,parts:2};const storage={getItem:()=>JSON.stringify(s),setItem:()=>{throw Error('disk full');}},store=new GameStore(storage,'workshop');store.state=s;const before=E.clone(s);await assert.rejects(store.run(d=>act(d,'upgradeBench',{id:b.id,level:2})),/disk full/);assert.deepEqual(s,before);const bad=E.clone(s);bad.thermal={wet:101,cold:0,heat:0,coat:false};assert.throws(()=>E.validateSave(bad),/冷暖/);b.workshopLevel=4;assert.throws(()=>E.validateSave(s),/等级/);});

test('larger complete rooms need more heat and heater corruption is rejected',()=>{const s=camp();const layout=end=>{const objects=[];for(let y=2;y<=end;y++)for(let x=2;x<=end;x++)objects.push({type:x===2||y===2||x===end||y===end?'wall':'roof',x,y,rot:0});objects.push({type:'heater',x:4,y:4,rot:0,heater:{lit:false,fuel:0,heat:18,at:s.time}});return {objects};};const small=roomTemperature(s,layout(6),[{x:3,y:3}]),large=roomTemperature(s,layout(8),[{x:3,y:3}]);assert(small.temperature>large.temperature+5);const h=room(s);h.heater={fuel:-1,heat:0,lit:false,at:s.time};assert.throws(()=>E.validateSave(s),/暖炉/);});

test('developer cold and wet locks apply throughout long thermal simulation',()=>{const s=game();s.world.environment={climate:'寒冷'};s.developer={enabled:true,timeLocked:false,locks:{cold:0,wet:0,heat:0,food:100,water:100}};E.tick(s,600,0);assert.equal(s.thermal.cold,0);assert.equal(s.thermal.wet,0);assert.equal(s.stats.health,100);});
