export const CLOTHES={cap:{name:'皮帽',slot:'head',weight:.3,armor:1,warmth:1,rain:.05,cost:{hide:1,cloth:1}},vest:{name:'皮护衣',slot:'torso',weight:1.2,armor:2,warmth:2,rain:.1,cost:{hide:3,cloth:2}},raincoat:{name:'防雨披衣',slot:'torso',weight:.7,armor:0,warmth:1,rain:.7,cost:{cloth:4,fuel:1}},warmcoat:{name:'保暖外套',slot:'torso',weight:1,armor:1,warmth:8,rain:.1},gloves:{name:'皮手套',slot:'hands',weight:.2,armor:1,warmth:1,rain:.05,cost:{hide:1,cloth:1}},trousers:{name:'厚布裤',slot:'legs',weight:.6,armor:1,warmth:2,rain:.1,cost:{cloth:3}},boots:{name:'皮靴',slot:'feet',weight:.8,armor:1,warmth:1,rain:.1,cost:{hide:2,cloth:1}}};
const tools={tool:{name:'工具',weight:1.5},stoneknife:{name:'石刀',weight:.4},woodspear:{name:'木矛',weight:1.2},stonespear:{name:'石矛',weight:1.6},bow:{name:'简易弓',weight:.8}};
export const DURABLE=Object.fromEntries(Object.entries({...tools,...CLOTHES}).flatMap(([base,r])=>Array.from({length:11},(_,n)=>[n===10?base:`${base}_d${n}`,{...r,base,condition:n,weapon:Object.hasOwn(tools,base),name:r.name+(n===10?'':n?`（耐久 ${n*10}%）`:'（损坏）')}] )));
export const DURABLE_ITEMS=Object.fromEntries(Object.entries(DURABLE).map(([id,r])=>[id,{name:r.name,weight:r.weight}]));
export const SLOTS={head:'头部',torso:'躯干',hands:'双手',legs:'腿部',feet:'脚部'};
export function worn(s){return s.wardrobe??(s.thermal?.coat?{torso:'warmcoat'}:{});}
export function clothingStats(s){let warmth=0,rain=0;for(const id of Object.values(worn(s))){const d=DURABLE[id];if(d){warmth+=(d.warmth??0)*d.condition/10;rain+=(d.rain??0)*d.condition/10;}}return {warmth,rain:Math.min(.9,rain)};}
export function wearItem(s,id,amount=1){const d=DURABLE[id];if(!d||!d.condition||!(s.bag[id]>0))return id;const n=Math.max(0,d.condition-amount),next=`${d.base}_d${n}`;if(!s.equipment&&id==='tool')s.equipment={weapon:'tool',stance:'walk'};s.bag[id]--;s.bag[next]=(s.bag[next]??0)+1;if(s.equipment?.weapon===id)s.equipment.weapon=n?next:null;if(!s.wardrobe&&s.thermal?.coat){s.wardrobe={torso:'warmcoat'};s.thermal.coat=false;}for(const slot of Object.keys(s.wardrobe??{}))if(s.wardrobe[slot]===id)s.wardrobe[slot]=next;return next;}
export function protect(s,part,damage){const slots=part==='head'?['head']:part==='torso'?['torso']:part.endsWith('Arm')?['hands']:['legs','feet'];let armor=0;for(const slot of slots){const id=worn(s)[slot],d=DURABLE[id];if(d?.condition){armor+=d.armor*d.condition/10;wearItem(s,id);}}return Math.max(0,damage-Math.floor(armor));}
export function validateDurables(s){if(s.wardrobe!==undefined){if(!s.wardrobe||typeof s.wardrobe!=='object'||Array.isArray(s.wardrobe))throw Error('穿戴记录无效');for(const[slot,id]of Object.entries(s.wardrobe))if(!Object.hasOwn(SLOTS,slot)||DURABLE[id]?.slot!==slot||!(s.bag[id]>0))throw Error('穿戴与物品不一致');}}
