import {randomAt} from './environment.js';
import {sightLine,localSight} from './daylight.js';
import {actorStep,blocked,occupied,distance,hitPlayer,combatLog} from './combat-data.js';
import {stealth} from './equipment-data.js';
export const NPC_KINDS={survivor:{name:'独行幸存者',hp:18,damage:2,armor:0,speed:1,bag:{water:2,canned:1}},trader:{name:'行脚商人',hp:24,damage:3,armor:1,speed:1,bag:{water:5,canned:3,bandage:2,drugs:1,cap:1}},raider:{name:'掠夺者',hp:22,damage:4,armor:1,speed:2,bag:{water:2,canned:1,scrap:2,vest:1}},wounded:{name:'受伤幸存者',hp:18,damage:1,armor:0,speed:1,bag:{water:1,herb:2}}};
export function ensureEncounters(s,m,t=s.time){if(!m||m.shore||m.encounters)return;const key=s.player.local.site,owner=m.owner??s.player,cell=s.world.cells[`${owner.x},${owner.y}`],roll=randomAt(s.seed+':npc:'+key,0,0),typeRoll=randomAt(s.seed+':npc-kind:'+key,0,0),kind=cell?.encounterHint?'survivor':typeRoll<.3?'trader':typeRoll<.6?'survivor':typeRoll<.8?'wounded':'raider';m.encounters={version:1,time:t,actors:[]};if(m.kind&&roll>.25&&!cell?.encounterHint)return;const spots=[];for(let y=1;y<m.h-1;y++)for(let x=1;x<m.w-1;x++)if(!blocked(m,x,y)&&distance({x,y},s.player.local)>=6&&!occupied(s,m,x,y))spots.push({x,y});if(!spots.length)return;const pos=spots[Math.floor(roll*spots.length)%spots.length],d=NPC_KINDS[kind];m.encounters.actors.push({id:'npc-1',name:d.name,kind,...pos,hp:kind==='wounded'?7:d.hp,bag:{...d.bag},hostile:kind==='raider',trust:0,state:'wander',born:t,deadAt:null,talked:false,helped:false,lastAttack:0});}
export function visibleNpcs(s){const m=s.player.local?s.locals[s.player.local.site]:null;return m?.encounters?.actors.filter(a=>localSight(s,m,s.player.local,a.x,a.y))??[];}
export function npcMinute(s,m,t,present=true){if(!m.encounters)return;const p=present&&s.player.local&&s.locals[s.player.local.site]===m&&s.stats.health>0?s.player.local:null;for(const a of m.encounters.actors){if(a.hp<=0||a.born>t)continue;const def=NPC_KINDS[a.kind],animal=(m.wildlife?.animals??[]).find(b=>b.hp>0&&['wolf','boar'].includes(b.species)&&distance(a,b)<=3&&sightLine(m,a,b.x,b.y,5)),enemy=m.encounters.actors.find(b=>b!==a&&b.hp>0&&b.born<=t&&a.hostile!==b.hostile&&sightLine(m,a,b.x,b.y,6)),detect=p&&a.hostile&&sightLine(m,a,p.x,p.y,(s.combat?.noiseUntil>=t?8:stealth(s)?2:6)),target=detect?p:animal??enemy;
 if(target){a.target={x:target.x,y:target.y,until:t+6};const flee=a.hp<=def.hp*.3||a.kind==='wounded';a.state=flee?'flee':'fight';if(!flee&&distance(a,target)<=1&&t-a.lastAttack>=2){a.lastAttack=t;if(target===p)hitPlayer(s,def.damage,a.name,t);else{target.hp=Math.max(0,target.hp-def.damage);if(!target.hp){target.deadAt=t;target.state='dead';if(target.species){target.meat=target.species==='boar'?3:2;target.hide=target.species==='boar'?2:1;target.target=null;m.wildlife.deaths++;}}}continue;}for(let n=0;n<def.speed;n++){const step=actorStep(s,m,a,target,flee);if(step)Object.assign(a,step);}continue;}
 if(a.target&&a.target.until>=t){a.state='search';const step=actorStep(s,m,a,a.target);if(step)Object.assign(a,step);}else{delete a.target;a.state='wander';if(t%5===0){const step=actorStep(s,m,a,{x:1+Math.floor(randomAt(s.seed+a.id,t,1)*(m.w-2)),y:1+Math.floor(randomAt(s.seed+a.id,t,2)*(m.h-2))});if(step)Object.assign(a,step);}}
 }m.encounters.time=Math.max(m.encounters.time,t);}
export function animalThreatTurn(s,m,a,t,present=true){if(a.hp<=0||!['wolf','boar'].includes(a.species))return false;const p=present&&s.player.local&&s.locals[s.player.local.site]===m&&s.stats.health>0?s.player.local:null,npc=m.encounters?.actors.find(n=>n.hp>0&&n.born<=t&&distance(a,n)<=4&&sightLine(m,a,n.x,n.y,6)),detect=p&&distance(a,p)<=(stealth(s)?1:a.species==='wolf'?6:2)&&sightLine(m,a,p.x,p.y,6),target=detect?p:npc;if(!target)return false;if(a.species==='wolf'&&(m.wildlife?.animals??[]).some(b=>b.hp===0&&t-b.deadAt<720&&b.meat>0&&distance(a,b)<=1)&&a.hunger>5&&!a.fear)return false;if(a.species==='wolf'&&a.hunger<35&&distance(a,target)>2)return false;if(a.species==='wolf'&&(m.wildlife?.animals??[]).some(b=>b.hp>0&&['rabbit','deer','rat'].includes(b.species)&&distance(a,b)<distance(a,target)&&sightLine(m,a,b.x,b.y,6)))return false;const flee=a.hp<=2||a.fear&&a.fear.until>=t;a.state=flee?'flee':'hunt';a.target=null;if(!flee&&distance(a,target)<=1){if(t-(a.attackAt??0)>=2){a.attackAt=t;if(target===p)hitPlayer(s,a.species==='wolf'?3:4,a.species==='wolf'?'狼':'野猪',t);else{target.hp=Math.max(0,target.hp-3);if(!target.hp){target.deadAt=t;target.state='dead';}}}return true;}for(let n=0;n<(a.species==='wolf'?3:2);n++){const step=actorStep(s,m,a,target,flee);if(step)Object.assign(a,step);}return true;}
export function validateEncounters(s,inventory){for(const m of Object.values(s.locals)){const e=m.encounters;if(e===undefined)continue;if(!e||e.version!==1||!Number.isSafeInteger(e.time)||e.time<0||e.time>s.time||!Array.isArray(e.actors)||e.actors.length>6)throw Error('NPC 存档无效');const ids=new Set(),positions=new Set();for(const a of e.actors){const d=NPC_KINDS[a.kind];if(!d||typeof a.id!=='string'||a.id.length>80||ids.has(a.id)||positions.has(`${a.x},${a.y}`)||typeof a.name!=='string'||a.name.length>60||!Number.isInteger(a.hp)||a.hp<0||a.hp>d.hp||!Number.isInteger(a.x)||!Number.isInteger(a.y)||blocked(m,a.x,a.y)||typeof a.hostile!=='boolean'||!Number.isInteger(a.trust)||a.trust<0||a.trust>3||typeof a.talked!=='boolean'||typeof a.helped!=='boolean'||!Number.isSafeInteger(a.born)||a.born<0||a.born>s.time||!Number.isSafeInteger(a.lastAttack)||a.lastAttack<0||a.lastAttack>s.time||!['wander','fight','search','flee','dead'].includes(a.state)||!(a.hp>0?a.deadAt===null&&a.state!=='dead':a.state==='dead'&&Number.isSafeInteger(a.deadAt)&&a.deadAt>=a.born&&a.deadAt<=s.time)||a.target&&(!Number.isInteger(a.target.x)||!Number.isInteger(a.target.y)||a.target.x<0||a.target.x>=m.w||a.target.y<0||a.target.y>=m.h||!Number.isInteger(a.target.until)||a.target.until<0||a.target.until>s.time+6))throw Error('NPC 状态无效');ids.add(a.id);positions.add(`${a.x},${a.y}`);inventory(a.bag);}}}
