import * as E from './engine.js';
import {visibleNpcs,NPC_KINDS} from './encounter-data.js';
import {distance,actorStep,blocked,occupied} from './combat-data.js';
import {weapon,bowChance} from './equipment-data.js';
import {wearItem} from './durable-data.js';
import {randomAt} from './environment.js';
export const TRADE={water:{pay:'wood',qty:1},canned:{pay:'scrap',qty:1},bandage:{pay:'cloth',qty:2},drugs:{pay:'scrap',qty:3},cap:{pay:'hide',qty:2}};
export function encounterAction(s,action,p={}){E.assert(!s.ended,'角色已无法行动');const m=E.localMap(s);E.assert(m,'请进入地点地图');if(action==='guard'){s.combat??={hits:0,guardUntil:0,noiseUntil:0};s.combat.guardUntil=s.time+3;E.tick(s,1,0);E.log(s,'防御姿态：三分钟内每次受击额外减伤 1。');return;}if(action==='escape'){E.assert(s.stats.stamina>=4,'体力不足');const threats=[...(m.wildlife?.animals??[]).filter(a=>a.hp>0&&['wolf','boar'].includes(a.species)),...(m.encounters?.actors??[]).filter(a=>a.hp>0&&a.hostile)].filter(a=>E.canSee(s,a.x,a.y)).sort((a,b)=>E.interactionDistance(s,a.x,a.y)-distance(b,s.player.local));E.assert(threats.length,'当前未看见可逃离的威胁');let moved=0;for(let n=0;n<2;n++){const step=actorStep(s,m,s.player.local,threats[0],true);if(step&&m.seen[E.key(step.x,step.y)]){Object.assign(s.player.local,step);moved++;}}E.assert(moved,'没有已知的安全撤退位置');s.stats.stamina-=4;E.tick(s,1,0);E.log(s,`紧急撤退 ${moved} 格。`);return;}
 const a=visibleNpcs(s).find(a=>a.id===p.id);E.assert(a,'目标不在视野内');const near=E.interactionDistance(s,a.x,a.y)<=1;if(action==='npcAttack'){const w=weapon(s),shoot=w.id==='bow';E.assert(a.hp>0&&E.interactionDistance(s,a.x,a.y)<=w.range,'目标已经死亡或超出射程');E.assert(s.stats.stamina>=4,'体力不足');E.assert(!shoot||s.bag.arrow>0,'没有箭矢');if(shoot)s.bag.arrow--;s.stats.stamina-=4;a.hostile=true;const success=!shoot||randomAt(s.seed+':npc-hit',s.revision,s.time)<bowChance(s,E.interactionDistance(s,a.x,a.y));if(success)a.hp=Math.max(0,a.hp-Math.max(1,w.damage-NPC_KINDS[a.kind].armor));if(!a.hp){a.deadAt=s.time;a.state='dead';delete a.target;}if(w.item)wearItem(s,w.item);s.combat??={hits:0,guardUntil:0,noiseUntil:0};s.combat.noiseUntil=s.time+3;E.tick(s,1,0);E.log(s,`攻击${a.name}：${success?'命中':'未命中'}。`);return;}
 E.assert(near,'请走到 NPC 同格或相邻位置');if(action==='npcLoot'){E.assert(a.hp===0,'只能取走尸体物资');E.transfer(a.bag,s.bag,p.item,1,20,s);E.log(s,`从${a.name}遗体拿取${E.ITEMS[p.item].name}。`);return;}E.assert(a.hp>0&&!a.hostile,'对方死亡或处于敌对状态');if(action==='npcTalk'){E.assert(!a.talked,'这条线索已经听过');a.talked=true;a.trust=Math.min(3,a.trust+1);const c=Object.values(s.world.cells).find(c=>c.site&&!(c.x===s.player.x&&c.y===s.player.y));if(c&&s.clues.length<200)s.clues.push({id:`npc-${s.player.local.site}-${a.id}`,kind:'rumor',title:c.name,detail:`${a.name}提到该处可能有可用物资，尚未核实。`,x:c.x,y:c.y,sourceName:a.name});E.tick(s,2,0);E.log(s,`${a.name}：${c?`“可以去 ${c.x},${c.y} 的${c.name}看看，我不能保证那里还安全。”`:'“我也正在找安全的落脚处。”'}`);return;}
 if(action==='npcAid'){E.assert(a.hp<NPC_KINDS[a.kind].hp&&!a.helped,'对方不需要更多救助');E.assert(s.bag.bandage>0||s.bag.wrap>0,'需要绷带或包扎布');s.bag[s.bag.bandage>0?'bandage':'wrap']--;E.tick(s,5,0);if(!s.ended&&a.hp>0){a.hp=Math.min(NPC_KINDS[a.kind].hp,a.hp+8);a.helped=true;a.trust=Math.min(3,a.trust+2);}E.log(s,'救助行动完成；对方的存活情况以现场为准。');return;}
 E.assert(action==='npcTrade'&&a.kind==='trader','对方不能交易');const trade=TRADE[p.item];E.assert(trade&&a.bag[p.item]>0&&(s.bag[trade.pay]??0)>=trade.qty,'货物售罄或交换材料不足');E.assert(E.weight(s.bag)-E.ITEMS[trade.pay].weight*trade.qty+E.ITEMS[p.item].weight<=20,'背包空间不足');E.transfer(s.bag,a.bag,trade.pay,trade.qty,200,s);E.transfer(a.bag,s.bag,p.item,1,20,s);E.tick(s,1,0);E.log(s,`换得${E.ITEMS[p.item].name} 1。`);}
