import * as E from './engine.js';
import {DURABLE,CLOTHES,SLOTS,worn,clothingStats} from './durable-data.js';
import {NPC_KINDS,visibleNpcs} from './encounter-data.js';
import {TRADE} from './encounters.js';
import {weapon,cuttingTool} from './equipment-data.js';
import {salvageRecipe,itemSalvage,PACKED} from './salvage.js';
import {activeEvents,EVENT_NAMES} from './events.js';
import {TRAP_ITEMS,TRAP_RECIPES} from './traps.js';
import {hasFacility} from './shelter-data.js';
import {sourceReachable} from './water-data.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(action,label,data={},disabled=false)=>`<button type="button" data-action="${action}" ${Object.entries(data).map(([k,v])=>`data-${k}="${esc(v)}"`).join(' ')} ${disabled?'disabled':''}>${esc(label)}</button>`;
const cost=items=>Object.entries(items).map(([id,q])=>`${E.ITEMS[id].name} ${q}`).join('、');
export function clothesPanel(s,craft=false){const wornItems=worn(s),stats=clothingStats(s);return `<section class="fs-survival-panel"><h3>穿戴与防护</h3><p>保暖 +${stats.warmth.toFixed(1)}°C · 减少淋湿 ${Math.round(stats.rain*100)}%。受击部位的护具提供减伤并磨损；武器每次攻击磨损 10%。</p><div class="fs-gear-slots">${Object.entries(SLOTS).map(([slot,name])=>`<div><small>${name}</small><b>${esc(E.ITEMS[wornItems[slot]]?.name??'未穿戴')}</b>${wornItems[slot]?btn('unequipClothes','脱下',{slot}):''}</div>`).join('')}</div>${Object.entries(s.bag).filter(([id,q])=>q>0&&DURABLE[id]?.slot&&DURABLE[id].condition>0&&wornItems[DURABLE[id].slot]!==id).map(([id])=>btn('equipClothes','穿戴 '+E.ITEMS[id].name,{item:id})).join('')}<details><summary>维修装备 · 工作台 / 20 分钟</summary><p>武器：木材 1、金属零件 1；衣物：布料 2。恢复至 100%。</p>${Object.keys(s.bag).filter(id=>s.bag[id]>0&&DURABLE[id]?.condition<10).map(id=>btn('repairDurable','修复 '+E.ITEMS[id].name,{item:id},!hasFacility(s,'bench'))).join('')||'<p>没有需要维修的装备。</p>'}</details><details><summary>拆解随身物品 · 10 分钟</summary>${Object.keys(s.bag).filter(id=>s.bag[id]>0&&itemSalvage(id)).map(item=>btn('dismantleItem',`${E.ITEMS[item].name} → ${cost(itemSalvage(item))}`,{item},Object.values(wornItems).includes(item)||weapon(s).item===item)).join('')}</details>${craft?`<details open><summary>制作衣物 · 工作台 / 30 分钟</summary>${Object.entries(CLOTHES).filter(([,d])=>d.cost).map(([item,d])=>`<p>${esc(d.name)} · 护甲 ${d.armor} · 保暖 ${d.warmth}°C<br>${cost(d.cost)}</p>${btn('craftClothes','制作 '+d.name,{item},!hasFacility(s,'bench'))}`).join('')}</details>`:''}</section>`;}
export function encounterPanel(s){const m=E.localMap(s);if(!m||m.shore)return '';const actors=visibleNpcs(s),w=weapon(s);return `<section class="fs-survival-panel"><h3>现场人物与威胁</h3><p>红色人物可能主动攻击；行动推进时间时，生物也会移动。潜行可缩短被发现距离。</p><div class="fs-row">${btn('guard','防御 · 1 分钟')}${btn('escape','紧急撤退 · 1 分钟 / 4 体力')}</div>${actors.map(a=>{const near=E.interactionDistance(s,a.x,a.y)<=1,d=NPC_KINDS[a.kind];return `<article class="fs-npc-card ${a.hostile?'fs-hostile':''}"><b>${esc(a.name)}</b><small>${a.hp<=0?'遗体':a.hostile?'敌对':'中立'} · ${a.x},${a.y} · 信任 ${a.trust}/3</small><progress max="${d.hp}" value="${a.hp}"></progress><span>生命 ${a.hp}/${d.hp} · ${esc({wander:'徘徊',fight:'交战',search:'搜索',flee:'逃离',dead:'死亡'}[a.state])}</span>${btn('select','在地图定位',{x:a.x,y:a.y})}${a.hp>0?`${btn('npcAttack',w.id==='bow'?'射击 · 1 分钟':'攻击 · 1 分钟',{id:a.id},E.interactionDistance(s,a.x,a.y)>w.range)}${!a.hostile?`<label>与对方说话<textarea data-npc-message="${esc(a.id)}" maxlength="600" rows="2" placeholder="通过独立 API 交流；台词不直接改变物资"></textarea></label>${btn('npcChat','交谈 · 2 分钟',{id:a.id},!near)}${btn('npcTalk','询问线索 · 2 分钟',{id:a.id},!near||a.talked)}${btn('npcAid','包扎救助 · 5 分钟',{id:a.id},!near||a.helped||a.hp>=d.hp)}${a.kind==='trader'?`<details><summary>交换物资</summary>${Object.entries(TRADE).filter(([id])=>a.bag[id]>0).map(([item,t])=>btn('npcTrade',`${E.ITEMS[item].name} ×1（存货 ${a.bag[item]}）← ${E.ITEMS[t.pay].name} ${t.qty}`,{id:a.id,item},!near)).join('')}</details>`:''}`:''}`:Object.entries(a.bag).filter(([,q])=>q>0).map(([item,q])=>btn('npcLoot',`拿取${E.ITEMS[item].name} · 剩余 ${q}`,{id:a.id,item},!near)).join('')}</article>`;}).join('')||'<p class="fs-muted">当前视野内没有人物。</p>'}</section>`;}
export function salvagePanel(s,c){if(!c||c.removed||!E.canSee(s,c.x,c.y))return '';const r=salvageRecipe(c),ready=c.searched&&!Object.values(c.items).some(q=>q>0)&&E.adjacent(s,c.x,c.y);return `<section class="fs-survival-panel"><h3>家具处理</h3><p>先搜索并取空。拆解后获得：${cost(r.items)}；原位置永久清空。</p>${btn('dismantle',`拆解 · ${r.cost} 分钟`,{x:c.x,y:c.y},!ready||!cuttingTool(s))}${r.pack?btn('packFurniture','打包搬回 · 10 分钟',{x:c.x,y:c.y},!ready):''}</section>`;}
export function packedPanel(s){const held=Object.keys(PACKED).filter(id=>s.bag[id]>0);return held.length?`<section class="fs-card"><h3>搬回的家具</h3><p>安置在空位后，可在布置模式调整位置。</p>${held.map(item=>btn('deployFurniture',`安置${E.ITEMS[item].name} · 15 分钟`,{item},!s.player.camp)).join('')}</section>`:'';}
export function trapCraftPanel(){return `<section class="fs-survival-panel"><h3>陷阱制作</h3>${Object.entries(TRAP_RECIPES).map(([item,r])=>`<p>${E.ITEMS[item].name}：${cost(r)}</p>${btn('craftTrap','制作 · 20 分钟',{item})}`).join('')}<p>在区域地图布置，消耗一份新鲜浆果、谷物或食品作诱饵。六小时后检查，每轮最多一份捕获物。</p></section>`;}
export function explorationPanel(s,c){if(!c?.known)return '';const here=!s.player.local&&!s.player.camp&&(c.terrain==='w'?sourceReachable(s,c):c.x===s.player.x&&c.y===s.player.y),item=c.terrain==='w'?'fishbasket':'snare';return `<section class="fs-survival-panel"><h3>地点变化与陷阱</h3>${activeEvents(s,c).map(e=>`<p>${EVENT_NAMES[e.kind]} · 剩余 ${Math.max(0,e.until-s.time)} 分钟${e.kind==='flood'?' · 进入该格额外 2 分钟':''}</p>${btn('investigateEvent','调查 · 10 分钟',{id:e.id},!here)}`).join('')||'<p class="fs-muted">暂无新的异常迹象。</p>'}${btn('placeTrap',`布置${TRAP_ITEMS[item].name} · 5 分钟`,{x:c.x,y:c.y,item},!here||!s.bag[item]||(c.traps?.length??0)>=3)}${(c.traps??[]).map(t=>`<div class="fs-npc-card"><b>${TRAP_ITEMS[t.type].name}</b><small>${t.checked?'本轮已检查':s.time>=t.ready?'可以检查捕获物':`还需 ${t.ready-s.time} 分钟`}</small>${btn(t.checked?'rearmTrap':'checkTrap',t.checked?'重新放饵 · 5 分钟':'检查 · 5 分钟',{x:c.x,y:c.y,id:t.id},!here||!t.checked&&s.time<t.ready)}${t.checked?btn('retrieveTrap','收回 · 5 分钟',{x:c.x,y:c.y,id:t.id},!here):''}</div>`).join('')}</section>`;}
