import {limbPenalty} from './body-data.js';
export const MEDICAL_ITEMS={herb:{name:'草药',weight:.1},simpledrug:{name:'简易药物',weight:.1},drugs:{name:'药物',weight:.1},wrap:{name:'包扎布',weight:.1},bandage:{name:'绷带',weight:.1},...Object.fromEntries([5,4,3,2,1].map(n=>[n===5?'medkit':`medkit${n}`,{name:`医药箱（余 ${n} 次）`,weight:.6}]))};
export const MEDICAL_RULES={herb:{chance:.3,minutes:10},simpledrug:{chance:.6,minutes:10},drugs:{chance:.9,minutes:10},medicine:{chance:.9,minutes:10},wrap:{bleeding:1,trauma:2,minutes:5},bandage:{bleeding:3,trauma:5,minutes:5},...Object.fromEntries([5,4,3,2,1].map(n=>[n===5?'medkit':`medkit${n}`,{chance:.9,bleeding:2,trauma:8,health:5,minutes:10,charges:n}]))};
export const MEDICAL_RECIPES={wrap:{name:'制作包扎布',cost:{cloth:1},output:{wrap:2},minutes:5},simpledrug:{name:'提炼简易药物',cost:{herb:3},output:{simpledrug:1},minutes:15,bench:true}};
export const coldLevel=s=>s.disease?.coldUntil>s.time?s.disease.cold:0;
export const medicalRecovery=(s,minutes=1)=>Math.max(.4,1-coldLevel(s)*.15*Math.min(minutes,Math.max(0,(s.disease?.coldUntil??0)-s.time))/minutes-limbPenalty(s).head*.003);
export function diseaseMinute(s,t){const d=s.disease??={cold:0,coldUntil:0,exposure:0};if(d.coldUntil<=t){d.cold=0;d.coldUntil=0;}if((s.thermal?.cold??0)>=40&&(s.thermal?.wet??0)>=40)d.exposure++;else d.exposure=Math.max(0,d.exposure-2);if(d.exposure>=180){d.exposure=0;d.cold=Math.min(3,d.cold+1);d.coldUntil=t+1+2880;}if(d.cold){s.stats.water=Math.max(0,s.stats.water-d.cold*.005);if(d.cold===3)s.stats.health=Math.max(0,s.stats.health-.005);}}
export function validateMedical(s){const d=s.disease;if(d!==undefined&&(!d||!Number.isInteger(d.cold)||d.cold<0||d.cold>3||!Number.isInteger(d.exposure)||d.exposure<0||d.exposure>=180||!Number.isSafeInteger(d.coldUntil)||d.coldUntil<0||d.coldUntil>s.time+2880))throw Error('疾病记录无效');if(s.medical!==undefined&&(!s.medical||!Number.isSafeInteger(s.medical.attempts)||s.medical.attempts<0||s.medical.attempts>1e9))throw Error('医疗尝试记录无效');}

export function medicalConditions(s){const w=s.injuries;return [w?.trauma>=30?'疼痛':null,w?.infection>=2||coldLevel(s)===3?'发热':null,coldLevel(s)||s.stats.stamina<25?'虚弱':null].filter(Boolean);}
