import * as E from './engine.js';
import {BODY_PARTS,ensureBody,bodyState,syncBody} from './body-data.js';
import {MEDICAL_RULES,MEDICAL_RECIPES,coldLevel} from './medical-data.js';
import {stomachLevel} from './water-data.js';
import {randomAt} from './environment.js';
import {hasFacility} from './shelter-data.js';
export function medicalPlan(s,item,target){E.assert(!s.ended,'角色已无法行动');const r=MEDICAL_RULES[item];E.assert(Object.hasOwn(MEDICAL_RULES,item),'请选择医疗物品');E.assert(s.bag[item]>0,'背包没有该医疗物品');if(Object.hasOwn(BODY_PARTS,target)){const w=bodyState(s)[target];E.assert(r.bleeding?(w.trauma>0||w.bleeding>0||r.chance&&w.infection>0):w.infection>0,r.bleeding?'这个部位没有需要处理的伤口':'药物只用于伤口感染或疾病');}else{E.assert(['stomach','cold'].includes(target),'请选择身体部位或疾病');E.assert(r.chance,'包扎物不能治疗全身疾病');E.assert(target==='stomach'?stomachLevel(s)>0:coldLevel(s)>0,'目前没有该疾病');}return r;}
export function medicalAction(s,action,p={}){E.assert(!s.ended,'角色已无法行动');if(action==='medicalCraft'){const r=MEDICAL_RECIPES[p.recipe];E.assert(Object.hasOwn(MEDICAL_RECIPES,p.recipe),'未知医疗配方');E.assert(!r.bench||hasFacility(s,'bench'),'提炼简易药物需要使用工作台');E.assert(E.weight(s.bag)-E.weight(r.cost)+E.weight(r.output)<=20,'背包空间不足');for(const[id,q]of Object.entries(r.cost))E.assert((s.bag[id]??0)>=q,'材料不足');for(const[id,q]of Object.entries(r.cost))s.bag[id]-=q;E.tick(s,r.minutes,0);if(!s.ended){for(const[id,q]of Object.entries(r.output))s.bag[id]=(s.bag[id]??0)+q;E.log(s,`完成${r.name}。`);}return;}
 E.assert(action==='medicalTreat','未知医疗操作');const r=medicalPlan(s,p.item,p.target),limb=Object.hasOwn(BODY_PARTS,p.target);if(limb)ensureBody(s);s.bag[p.item]--;if(r.charges>1){const next=`medkit${r.charges-1}`;s.bag[next]=(s.bag[next]??0)+1;}s.medical??={attempts:0};s.medical.attempts++;const success=!r.chance||randomAt(s.seed+':medical',s.medical.attempts,0)<r.chance;E.tick(s,r.minutes,0);if(s.ended){E.log(s,'治疗过程中健康耗尽，物资已消耗。');return;}let treated=false;if(limb){const w=s.injuries.limbs[p.target];if(r.bleeding){w.bleeding=Math.max(0,w.bleeding-r.bleeding);w.trauma=Math.max(0,w.trauma-r.trauma);if(!w.bleeding)w.exposure=0;}if(r.chance&&w.infection>0){treated=true;if(success)w.infection--; }syncBody(s);}else{treated=true;if(success){if(p.target==='stomach'){s.waterHealth.severity=Math.max(0,s.waterHealth.severity-1);if(!s.waterHealth.severity)s.waterHealth.until=0;}else{s.disease.cold=Math.max(0,s.disease.cold-1);if(!s.disease.cold)s.disease.coldUntil=0;}}}if(r.health)s.stats.health=Math.min(100,s.stats.health+r.health);E.log(s,`使用${E.ITEMS[p.item].name}处理${BODY_PARTS[p.target]??(p.target==='stomach'?'肠胃不适':'风寒病')}：${r.bleeding&&limb?'固定包扎效果已生效。':''}${treated?(success?'药物治疗成功，严重程度降低一级。':'药物治疗未成功，已消耗本次物资。'):''}${r.charges?`医药箱剩余 ${r.charges-1} 次。`:''}`);
}
