import * as E from './engine.js';
import {cuttingTool} from './equipment-data.js';
import {DURABLE,wearItem,worn} from './durable-data.js';
import {FURNITURE,campAt,campSize,placementError} from './camp-data.js';
export const PACKED={packedbox:{name:'打包储物箱',weight:4,type:'box'},packedchair:{name:'打包椅子',weight:2,type:'chair'}};
export function itemSalvage(id){const d=DURABLE[id];return d?(d.weapon?{scrap:1}:{cloth:1}):id==='book'?{fuel:1}:id==='electronics'?{components:2}:null;}
export function salvageRecipe(c){return /电|机器|冰箱|收音/.test(c.name+c.kind)?{cost:20,items:{scrap:2,components:2},pack:null}:/床|沙发/.test(c.name+c.kind)?{cost:20,items:{wood:2,cloth:2},pack:null}:/椅|凳/.test(c.name+c.kind)?{cost:10,items:{wood:1},pack:'packedchair'}:{cost:15,items:{wood:2,scrap:1},pack:'packedbox'};}
export function salvageAction(s,action,p){E.assert(!s.ended,'角色已无法行动');if(action==='dismantleItem'){const output=itemSalvage(p.item);E.assert(output&&s.bag[p.item]>0,'物品无法拆解');E.assert(!Object.values(worn(s)).includes(p.item)&&(s.equipment?.weapon??(!s.equipment?'tool':null))!==p.item,'先卸下装备');E.assert(E.weight(s.bag)-E.ITEMS[p.item].weight+E.weight(output)<=20,'背包空间不足');s.bag[p.item]--;E.tick(s,10,0);if(!s.ended)for(const[id,q]of Object.entries(output))s.bag[id]=(s.bag[id]??0)+q;E.log(s,'物品已拆成材料。');return;}if(action==='deployFurniture'){E.assert(s.player.camp&&PACKED[p.item]&&s.bag[p.item]>0,'请在营地部署携带的家具');const l=campAt(s).layout,type=PACKED[p.item].type;let o;for(let y=1;y<campSize(l)-1&&!o;y++)for(let x=1;x<campSize(l)-1&&!o;x++){const v={id:'f'+(l.serial+1),type,x,y,rot:0,name:FURNITURE[type].name,...(type==='box'?{items:{}}:{})};if(!placementError(l,v,s.player.camp))o=v;}E.assert(o,'没有可用的家具位置');s.bag[p.item]--;E.tick(s,15,0);if(!s.ended){l.serial++;l.objects.push(o);E.log(s,'搬回的家具已安置，可切换布置模式调整位置。');}return;}
 const m=E.localMap(s),c=m?.containers[E.key(p.x,p.y)];E.assert(m&&!m.kind&&c&&!c.removed&&E.canSee(s,c.x,c.y)&&E.adjacent(s,c.x,c.y),'请走到可见建筑家具旁');E.assert(c.searched&&!Object.values(c.items).some(n=>n>0),'先搜索并取空家具');const r=salvageRecipe(c),pack=action==='packFurniture';E.assert(pack||action==='dismantle','未知拆解操作');E.assert(!pack||r.pack,'这件家具只能拆解');E.assert(pack||cuttingTool(s),'拆解需要可用工具或石刀');const items=pack?{[r.pack]:1}:r.items;E.assert(E.weight(s.bag)+E.weight(items)<=20,'背包空间不足');E.tick(s,pack?10:r.cost,0);if(s.ended)return;c.removed=pack?'packed':'dismantled';for(const[id,n]of Object.entries(items))s.bag[id]=(s.bag[id]??0)+n;if(!pack){const tool=Object.keys(s.bag).find(id=>s.bag[id]>0&&DURABLE[id]?.condition>0&&['tool','stoneknife'].includes(DURABLE[id].base));wearItem(s,tool);}E.log(s,`${pack?'打包':'拆解'}${c.name}，原位置已清空。`);}
export function validateSalvage(s){for(const m of Object.values(s.locals))for(const c of Object.values(m.containers))if(c.removed!==undefined&&(m.kind||!['packed','dismantled'].includes(c.removed)||!c.searched||Object.values(c.items).some(n=>n>0)))throw Error('家具拆解记录无效');}
