import {activeBenefits,benefitsPanel} from './positive-states.js';
import {timeFrozen} from './developer-data.js';
import {ITEMS} from './engine.js';
import {foodBatches,freshQty} from './provisions.js';
import {FACILITIES,currentCamp,hasFacility} from './shelter-data.js';
import {injuryState} from './injury-data.js';
const btn=(a,label,item='',disabled=false)=>`<button type="button" data-action="${a}" data-item="${item}" ${disabled?'disabled':''}>${label}</button>`;
export function foodPanel(s,bag=s.bag,where='bag'){
 const batches=foodBatches(s,bag),ids=[...new Set(batches.map(b=>b.id))],rate=where==='camp'&&s.world.cells[`${s.player.x},${s.player.y}`]?.camp?.facilities?.cellar?.25:1;
 return `<section class="fs-survival-panel"><h3>食物保存${where==='camp'?' · 营地':''}</h3>${ids.map(id=>{const lots=batches.filter(b=>b.id===id),fresh=lots.filter(b=>b.life>0),bad=lots.filter(b=>!b.life).reduce((n,b)=>n+b.qty,0),next=fresh.length?Math.min(...fresh.map(b=>b.life))/rate:0;return `<p><b>${ITEMS[id].name}</b> · 可用 ${fresh.reduce((n,b)=>n+b.qty,0)} / 腐败 ${bad}<br><small>${next?`最早约 ${Math.ceil(next/60)} 小时后腐败`:'无可用批次'}</small></p>`;}).join('')||'<p>暂无需要记录的食物。</p>'}<small>优先使用快过期的可用批次。腐败食物占重量，不能食用或加工。${where==='camp'&&rate<1?'地窖保存生效：变质速度为 ¼。':''}</small>${btn('discardFood','丢弃腐败食物',where,s.ended||where==='camp'&&!!s.player.local||!batches.some(b=>b.life===0))}</section>`;
}
export function injuryPanel(s){const w=injuryState(s);return benefitsPanel(s)+`<section class="fs-survival-panel"><small class="fs-kicker">CONDITION</small><h3>伤势与治疗</h3><div class="fs-tags"><span>创伤 ${Math.round(w.trauma)}/100</span><span>出血 ${w.bleeding}/3</span><span>感染 ${w.infection}/3</span></div><p>${w.bleeding||w.infection?`每小时约损失 ${(w.bleeding*.6+w.infection*.3).toFixed(1)} 健康；睡眠也会持续。`:'没有持续失血。'}普通行动基础体力消耗增加 ${Math.round(w.trauma)}%。${w.trauma>=30?'创伤较重，每格移动额外一分钟。':''}</p><div class="fs-action-list">${btn('bandage','包扎止血 · 布料 1 / 5 分钟','',s.ended||!w.bleeding||!s.bag.cloth)}${btn('treatInfection','医疗处理 · 医疗用品 1 / 10 分钟','',s.ended||(!w.trauma&&!w.bleeding&&!w.infection)||!s.bag.medicine)}</div><p class="fs-muted">医疗处理清除出血和感染、降低 20 创伤、恢复 10 健康。无出血与感染、饥渴均高于 20 时，休息或睡眠每小时恢复 2 创伤，营地床铺提高至 4。治疗完成前仍会失血。</p></section>`;}
export function facilityPanel(s,selected=null){const camp=currentCamp(s);return `<section class="fs-card"><small class="fs-kicker">SHELTER FACILITIES</small><h2>庇护所设施</h2>${!camp?'<p>请先返回区域地图上的庇护所。</p>':`<p>设施归属于当前营地，建成后永久生效。建设、加工材料从随身背包扣除。</p>${Object.entries(FACILITIES).filter(([id])=>!selected||id===selected).map(([id,r])=>`<details ${selected?'open':''}><summary>${r.name} · ${camp.facilities?.[id]?'已建成':'未建设'}</summary><p>${r.description}</p><small>${Object.entries(r.cost).map(([i,q])=>`${ITEMS[i].name} ${s.bag[i]??0}/${q}`).join(' · ')}</small>${btn('buildFacility',`建设${r.name} · ${r.minutes} 分钟`,id,s.ended||camp.facilities?.[id]||!!r.requires&&!camp.facilities?.[r.requires]||Object.entries(r.cost).some(([i,q])=>(s.bag[i]??0)<q))}</details>`).join('')}${!selected||['stove','smoker'].includes(selected)?`<h3>营地加工</h3><div class="fs-action-list">${btn('campCook','灶台烤肉 · 生肉 1 / 木材 1 / 15 分钟','',s.ended||!hasFacility(s,'stove')||!s.bag.wood||!freshQty(s,'rawmeat',s.bag,timeFrozen(s)?0:15))}${btn('smokeMeat','制作熏肉 · 生肉 1 / 木材 2 / 120 分钟','',s.ended||!hasFacility(s,'smoker')||(s.bag.wood??0)<2||!freshQty(s,'rawmeat',s.bag,timeFrozen(s)?0:120))}</div>`:''}`}</section>`;}
export function conditionSummary(s){const w=injuryState(s);return activeBenefits(s).map(r=>`<span class="fs-benefit-tag">${r.name} · ${r.remaining} 分钟</span>`).join('')+(w.trauma||w.bleeding||w.infection?`<span>伤势：创伤 ${Math.round(w.trauma)} · 出血 ${w.bleeding} · 感染 ${w.infection}</span><button type="button" data-tab="bag">查看与治疗</button>`:activeBenefits(s).length?'<button type="button" data-tab="bag">查看身体状况</button>':'');}
