import {diseaseMinute} from './medical-data.js';
import {devEnabled} from './developer-data.js';
import {campAt,tiles} from './camp-data.js';
import {campRooms,coverAt,campBed} from './camp-rooms.js';
import {waterWeather} from './water-data.js';
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
export function outdoorTemperature(s,t=s.time){const e=s.world.environment,base={寒冷:0,干旱:29,热带:27,温带:18}[e?.climate]??24,season=8*Math.sin(2*Math.PI*Math.floor(t/1440)/28),daily=4*Math.cos(2*Math.PI*(t%1440-900)/1440);return base+season+daily-(waterWeather(s,t)==='小雨'?2:0)-(e?.biome==='mountain'?4:0);}
export const heaterFuel=(o,t)=>Math.max(0,(o.heater?.fuel??0)-(o.heater?.lit?Math.max(0,t-o.heater.at):0));
export function heaterHeat(o,t,complete=false){const h=o.heater;if(!h)return 0;const elapsed=Math.max(0,t-h.at),burn=h.lit?Math.min(elapsed,h.fuel):0;return Math.max(0,Math.min(18,h.heat+burn*(complete?.2:.08))-(elapsed-burn)*(complete?.04:.15));}
export function roomTemperature(s,l,points,t=s.time){const cover=coverAt(l,points),region=cover.region,out=outdoorTemperature(s,t);let warmth=0;for(const o of l.objects.filter(a=>a.type==='heater')){const hc=coverAt(l,tiles(o)),same=region&&hc.region===region,near=points.some(p=>Math.abs(p.x-o.x)+Math.abs(p.y-o.y)<=2);if(cover.kind==='room'&&same)warmth+=heaterHeat(o,t,hc.kind==='room')*Math.min(1,9/Math.max(1,region.points.length));else if(near)warmth+=heaterHeat(o,t,false)*.25;}return {outdoor:out,temperature:out+Math.min(22,warmth),covered:cover.covered,label:cover.label,heated:warmth>1};}
export function thermalSnapshot(s,t=s.time,mode='normal'){const out=outdoorTemperature(s,t),l=campAt(s)?.layout;let place={outdoor:out,temperature:out,covered:false,label:'露天',heated:false};if(s.player.camp&&l){const bed=mode==='sleep'||s.campMode==='simple'?campBed(s):null;place=roomTemperature(s,l,bed?tiles(bed.bed):[s.player.camp],t);}else if(s.player.local){const m=s.locals[s.player.local.site],p=s.player.local,inside=m.grid[p.y]?.[p.x]!=='E';if(inside&&m.kind==='cave')place={...place,temperature:14,covered:true,label:'洞穴'};else if(inside&&!m.kind)place={...place,temperature:out,covered:true,label:'建筑内'};}else if(campAt(s)&&!l)place={...place,covered:true,label:'庇护所'};return place;}
export const thermalRecovery=s=>Math.max(.5,1-(s.thermal?.cold??0)*.003-(s.thermal?.heat??0)*.002);
export function advanceTemperature(s,from,effort=0,mode='normal'){s.thermal??={wet:0,cold:0,heat:0,coat:false};const state=s.thermal,lock=id=>{if(devEnabled(s)&&Object.hasOwn(s.developer.locks,id))state[id]=s.developer.locks[id];};for(let t=from;t<s.time;t++){const p=thermalSnapshot(s,t,mode),rain=!p.covered&&waterWeather(s,t)==='小雨';state.wet=clamp(state.wet+(rain?.6:p.heated?-.8:-.2));lock('wet');const temp=p.temperature-state.wet*.04+(state.coat&&p.temperature<20?8:0);state.cold=clamp(state.cold+(temp<12?(12-temp)/60:-.5));state.heat=clamp(state.heat+(temp>30?(temp-30)/60:-.5));lock('cold');lock('heat');diseaseMinute(s,t);if(state.cold>=40)s.stats.stamina=clamp(s.stats.stamina-.025*effort);if(state.heat>=40)s.stats.water=clamp(s.stats.water-.02);if(state.cold>=80||state.heat>=80)s.stats.health=clamp(s.stats.health-.01);if(p.heated&&p.temperature>=18&&p.temperature<=26&&state.wet<20)s.stats.spirit=clamp((s.stats.spirit??100)+1/60);}
 for(const c of Object.values(s.world.cells)){const l=c.camp?.layout;if(!l)continue;for(const o of l.objects.filter(a=>a.type==='heater'&&a.heater)){const h=o.heater,complete=coverAt(l,tiles(o)).kind==='room';h.heat=heaterHeat(o,s.time,complete);h.fuel=heaterFuel(o,s.time);h.at=s.time;if(!h.fuel)h.lit=false;}}
}
export function validateTemperature(s){const q=s.thermal;if(q!==undefined){if(!q||typeof q.coat!=='boolean'||['wet','cold','heat'].some(k=>!Number.isFinite(q[k])||q[k]<0||q[k]>100)||q.coat&&!(s.bag.warmcoat>0))throw Error('冷暖状态无效');}for(const c of Object.values(s.world.cells))for(const o of c.camp?.layout?.objects??[])if(o.heater!==undefined){const h=o.heater;if(o.type!=='heater'||!h||typeof h.lit!=='boolean'||!Number.isFinite(h.heat)||h.heat<0||h.heat>18||!Number.isInteger(h.fuel)||h.fuel<0||h.fuel>480||!Number.isSafeInteger(h.at)||h.at<0||h.at>s.time||h.lit&&!h.fuel)throw Error('暖炉状态无效');}}
