import {reserve} from './wildlife.js';
import * as E from './engine.js';
import {randomAt} from './environment.js';
import {gainFood,consumeFood,freshQty,FOOD_LIFE} from './provisions.js';
import {sourceReachable,fishingLeft} from './water-data.js';
export const TRAP_ITEMS={snare:{name:'小兽套索',weight:.4},fishbasket:{name:'捕鱼笼',weight:1}};
export const TRAP_RECIPES={snare:{wood:1,fiber:3},fishbasket:{wood:2,fiber:4}};
const reach=(s,c)=>!s.player.local&&!s.player.camp&&(c.terrain==='w'?sourceReachable(s,c):c.x===s.player.x&&c.y===s.player.y);
export function trapAction(s,action,p){E.assert(!s.ended,'角色已无法行动');if(action==='craftTrap'){const cost=TRAP_RECIPES[p.item];E.assert(Object.hasOwn(TRAP_RECIPES,p.item),'未知陷阱');for(const[id,q]of Object.entries(cost))E.assert(s.bag[id]>=q,'材料不足');E.assert(E.weight(s.bag)-E.weight(cost)+TRAP_ITEMS[p.item].weight<=20,'背包空间不足');for(const[id,q]of Object.entries(cost))s.bag[id]-=q;E.tick(s,20,0);if(!s.ended)s.bag[p.item]=(s.bag[p.item]??0)+1;return;}
 const c=E.cell(s,p.x,p.y);E.assert(c&&reach(s,c),'请在当前陆地格或相邻水域操作');const trap=c.traps?.find(t=>t.id===p.id);if(action==='placeTrap'||action==='rearmTrap'){const type=trap?.type??p.item;E.assert(Object.hasOwn(TRAP_ITEMS,type)&&(c.terrain==='w')===(type==='fishbasket'),'捕鱼笼需放水域，套索需放陆地');if(action==='rearmTrap')E.assert(trap&&trap.checked,'先检查上一轮陷阱');else E.assert((c.traps?.length??0)<3&&s.bag[type]>0,'每格最多三个陷阱，需携带成品');const bait=['berries','grain','food'].find(id=>freshQty(s,id)>0);E.assert(bait,'需要浆果、谷物或食品 1 作为诱饵');consumeFood(s,s.bag,bait);if(action==='placeTrap')s.bag[type]--;E.tick(s,5,0);if(s.ended)return;c.traps??=[];const t=trap??{id:`trap-${s.time}-${s.revision}-${c.traps.length}`,type};Object.assign(t,{placed:s.time,ready:s.time+360,checked:false});if(!trap)c.traps.push(t);E.log(s,'陷阱已布置，六小时后可检查；每轮最多捕获一份。');return;}
 E.assert(trap,'陷阱不存在');if(action==='retrieveTrap'){E.assert(trap.checked,'先检查并处理捕获物再收回');E.assert(E.weight(s.bag)+TRAP_ITEMS[trap.type].weight<=20,'背包空间不足');c.traps=c.traps.filter(t=>t.id!==p.id);s.bag[trap.type]=(s.bag[trap.type]??0)+1;E.tick(s,5,0);return;}
 E.assert(action==='checkTrap'&&!trap.checked&&s.time>=trap.ready,'陷阱尚未到检查时间或已经检查');const fish=trap.type==='fishbasket',stock=reserve(s,s.time).stock,available=fish?fishingLeft(s,c)>0:stock?stock.rabbit>=1:true,success=available&&randomAt(s.seed+':trap:'+trap.id,trap.placed,0)<(fish?.8:.65),item=fish?'fish':'rawmeat';E.assert(!success||E.weight(s.bag)+E.ITEMS[item].weight<=20,'背包空间不足');trap.checked=true;if(success){if(fish)c.fishing={bucket:Math.floor(s.time/720),catches:4-fishingLeft(s,c)};else if(stock)stock.rabbit--;const life=FOOD_LIFE[item]-(s.time-trap.ready);if(life>0)gainFood(s,s.bag,item,1,life);else E.log(s,'捕获物已经腐败，无法取用。');}E.tick(s,5,0);E.log(s,success?'本轮捕获已处理；新鲜度从六小时检查时点开始计算，腐败物无法带走。':'本轮没有捕获；可重新装填诱饵。');}
export function validateTraps(s){for(const c of Object.values(s.world.cells)){if(c.traps===undefined)continue;if(!Array.isArray(c.traps)||c.traps.length>3)throw Error('陷阱数量无效');const ids=new Set();for(const t of c.traps){if(typeof t.id!=='string'||t.id.length>100||ids.has(t.id)||!Object.hasOwn(TRAP_ITEMS,t.type)||(c.terrain==='w')!==(t.type==='fishbasket')||!Number.isSafeInteger(t.placed)||t.placed<0||t.placed>s.time||t.ready!==t.placed+360||typeof t.checked!=='boolean')throw Error('陷阱记录无效');ids.add(t.id);}}}
