import * as E from './engine.js';
import {randomAt} from './environment.js';
import {sourceReachable,shoreSpec,stomachLevel,settleRain} from './water-data.js';
import {campAt,canUseCampObject} from './camp-data.js';
import {hasFacility} from './shelter-data.js';
import {cookingReady} from './hunting.js';
export function waterAction(s,action,p={}){E.assert(!s.ended,'角色已无法行动');
 if(action==='enterShore'){const c=E.cell(s,p.x,p.y);E.assert(sourceReachable(s,c),'请站在已发现水域相邻的陆地上');const spec=shoreSpec(s,c);if(!s.locals[spec.id]){const m=E.validateLocal(spec,'small');Object.assign(m,{kind:'field',owner:{x:s.player.x,y:s.player.y},shore:{x:c.x,y:c.y},name:spec.description.split('，')[0],portals:[]});for(const o of Object.values(m.containers))o.searched=true;s.locals[spec.id]=m;}s.player.local={site:spec.id,...s.locals[spec.id].exit};E.tick(s,1);E.revealLocal(s);E.log(s,'进入岸边，水面不可步行。');return;}
 if(action==='collectWater'){const q=E.int(p.qty,1,5),m=E.localMap(s);if(m?.shore)E.assert(E.canSee(s,4,5)&&E.adjacent(s,4,5),'请走到岸边取水点旁');else E.assert(sourceReachable(s,E.cell(s,p.x,p.y)),'请站在水域相邻陆地上');E.assert(E.weight(s.bag)+q*.5<=20,'背包空间不足');E.tick(s,q*3,0);if(!s.ended){s.bag.dirtywater=(s.bag.dirtywater??0)+q;E.log(s,`采集污水 ${q} 份。`);}return;}
 if(action==='drinkDirty'){E.assert((s.bag.dirtywater??0)>0,'没有污水');s.bag.dirtywater--;s.stats.water=Math.min(100,s.stats.water+30);const w=s.waterHealth??={drinks:0,severity:0,until:0};w.drinks++;const sick=randomAt(s.seed+':dirty-water',w.drinks,23)<.6;if(sick){w.severity=Math.min(3,stomachLevel(s)+1);w.until=Math.min(s.time+1440,Math.max(s.time,w.until)+480);}E.log(s,sick?'冒险饮用污水，出现肠胃不适。':'冒险饮用污水，本次未出现不适。');return;}
 if(action==='treatStomach'){E.assert(stomachLevel(s)>0,'没有肠胃不适');E.assert((s.bag.medicine??0)>0,'需要医疗用品 1');s.bag.medicine--;E.tick(s,10,0);if(!s.ended){s.waterHealth.severity=Math.max(0,s.waterHealth.severity-1);if(!s.waterHealth.severity)s.waterHealth.until=0;E.log(s,'处理肠胃不适，严重程度降低一级。');}return;}
 if(action==='rainTake'||action==='rainEmpty'){E.assert(s.player.camp,'请进入营地');settleRain(s);const o=campAt(s).layout.objects.find(o=>o.id===p.id);E.assert(o?.type==='rainCollector'&&canUseCampObject(s,o),'请靠近雨水收集器，或使用简易模式');if(action==='rainEmpty'){o.rain=0;E.log(s,'已排空雨水收集器。');return;}const q=E.int(p.qty,1,5);E.assert(Math.floor(o.rain/15)>=q,'收集器内污水不足');E.assert(E.weight(s.bag)+q*.5<=20,'背包空间不足');o.rain-=q*15;s.bag.dirtywater=(s.bag.dirtywater??0)+q;E.log(s,`从收集器取出污水 ${q} 份，不耗时。`);return;}
 if(action==='craftFilter'){E.assert(hasFacility(s,'bench'),'需要使用营地工作台');E.assert((s.bag.cloth??0)>=1&&(s.bag.fuel??0)>=1,'需要布料 1、燃料 1');s.bag.cloth--;s.bag.fuel--;E.tick(s,10,0);if(!s.ended){s.bag.waterfilter=(s.bag.waterfilter??0)+1;E.log(s,'制成净水滤芯 1。');}return;}
 E.assert(['boilWater','filterWater'].includes(action),'未知水源操作');const filter=action==='filterWater',q=filter?5:1;E.assert((s.bag.dirtywater??0)>=q,`需要污水 ${q} 份`);if(filter){E.assert(hasFacility(s,'purifier'),'需要使用净水设备');E.assert((s.bag.waterfilter??0)>0,'需要净水滤芯 1');s.bag.waterfilter--;}else{const stove=hasFacility(s,'stove');E.assert(stove||cookingReady(s),'需要营地灶台，或靠近燃料至少够 10 分钟的营火');if(stove){E.assert((s.bag.fuel??0)>0,'需要燃料 1');s.bag.fuel--;}}s.bag.dirtywater-=q;E.tick(s,10,0);if(!s.ended){s.bag.water=(s.bag.water??0)+q;E.log(s,`净化完成，获得饮用水 ${q} 份。`);}
}
