import {stomachLevel,sourceReachable,waterLabel,rainCovered} from './water-data.js';
import {weight,localMap,localPath,routeMinutes,canSee,adjacent} from './engine.js';
import {campAt,canUseCampObject} from './camp-data.js';
import {hasFacility} from './shelter-data.js';
import {cookingReady} from './hunting.js';
const btn=(a,t,disabled=false,extra='')=>`<button type="button" data-action="${a}" ${extra} ${disabled?'disabled':''}>${t}</button>`;
export function regionWaterPanel(s,c){if(!c?.known||c.terrain!=='w')return '';const ready=sourceReachable(s,c),coord=`data-x="${c.x}" data-y="${c.y}"`;return `<section class="fs-survival-panel"><h3>${waterLabel(s,c)}水源</h3><p>站在相邻陆地可取水或进入岸边；水面不可步行，第一版不开放游泳。天然水源不因取水耗尽。</p>${btn('enterShore','进入岸边 · 1 分钟',!ready,coord)}${[1,5].map(q=>btn('collectWater',`收集污水 ${q} 份 · ${q*3} 分钟 / ${q*.5} kg`,!ready||weight(s.bag)+q*.5>20,`${coord} data-qty="${q}"`)).join('')}</section>`;}
export function shorePanel(s,x,y){const m=localMap(s),p=s.player.local,known=m.seen[`${x},${y}`],path=known?localPath(s,x,y):null,near=canSee(s,4,5)&&adjacent(s,4,5),exit=p.x===m.exit.x&&p.y===m.exit.y;return `<h2>${!known?'尚未看见':x>=5?'水面 · 不可步行':x===4&&y===5?'岸边取水点':'岸边'}</h2><p>沿岸移动，靠近取水点收集污水。每份 0.5 kg，耗时 3 分钟。</p>${btn('move',path?.length?`移动 · ${routeMinutes(s,path)} 分钟`:'移动到这里',!path?.length)}${btn('select','定位取水点',false,'data-x="4" data-y="5"')}${[1,5].map(q=>btn('collectWater',`收集污水 ${q} 份 · ${q*3} 分钟`,!near||weight(s.bag)+q*.5>20,`data-qty="${q}"`)).join('')}${btn('select','定位返回出口',false,`data-x="${m.exit.x}" data-y="${m.exit.y}"`)}${btn('leave','返回区域地图 · 1 分钟',!exit)}`;}
export function waterPanel(s){const level=stomachLevel(s);return `<section class="fs-survival-panel"><h3>水与净化</h3><p>污水 ${s.bag.dirtywater??0} · 饮用水 ${s.bag.water??0} · 滤芯 ${s.bag.waterfilter??0}</p><p>污水可恢复 30 水分，每次有 60% 游戏概率造成肠胃不适。清水不会触发此风险。</p>${btn('drinkDirtyPreview','冒险饮用污水 · 查看风险',!s.bag.dirtywater||s.ended)}${btn('boilWater','煮水 1 份 · 10 分钟',!s.bag.dirtywater||(!hasFacility(s,'stove')&&!cookingReady(s))||hasFacility(s,'stove')&&!s.bag.fuel)}<small>灶台消耗燃料 1；野外营火需够燃烧 10 分钟。煮水得到饮用水 1。</small>${btn('filterWater','过滤 5 份 · 滤芯 1 / 10 分钟',(s.bag.dirtywater??0)<5||!s.bag.waterfilter||!hasFacility(s,'purifier'))}${btn('craftFilter','制作滤芯 · 布料 1 / 燃料 1 / 10 分钟',!s.bag.cloth||!s.bag.fuel||!hasFacility(s,'bench'))}<p>${level?`肠胃不适 ${level}/3 · 约 ${s.waterHealth.until-s.time} 分钟后缓解；每小时额外消耗 ${level*1.2} 水分，体力恢复降低 ${level*15}%。${level===3?'重度每小时损失 0.9 健康。':''}`:'目前没有肠胃不适。'}</p>${btn('treatStomach','处理肠胃不适 · 医疗用品 1 / 10 分钟',!level||!s.bag.medicine)}<small>处理后严重程度降低一级。状态可自然消退；再次感染延长 8 小时并加重，最长剩余 24 小时。</small></section>`;}
export function collectorPanel(s,o){if(o?.type!=='rainCollector')return '';const l=campAt(s).layout,near=canUseCampObject(s,o),q=Math.floor(o.rain/15);return `<section class="fs-survival-panel"><h3>雨水储量 ${q}/20 份</h3><p>${rainCovered(l,o)?'屋顶遮挡，停止接雨':'露天接雨：小雨每小时 4 份污水'}；未满一份的进度 ${o.rain%15}/15。雨停后保留已有水。</p>${[1,5].map(n=>btn('rainTake',`取出污水 ${n} 份 · 不耗时`,!near||q<n||weight(s.bag)+n*.5>20,`data-id="${o.id}" data-qty="${n}"`)).join('')}${btn('rainEmpty','排空收集器（丢弃余水）',!near||!o.rain,`data-id="${o.id}"`)}</section>`;}
