import {randomAt} from './environment.js';
import {tiles} from './camp-data.js';
export const waterDepth=(s,c)=>c?.terrain==='w'?(randomAt(`${s.seed}:water:${s.atlas.x},${s.atlas.y}`,c.x,c.y)<.65?'shallow':'deep'):null;
export const waterLabel=(s,c)=>waterDepth(s,c)==='deep'?'深水':'浅水';
export function sourceReachable(s,c){return !s.player.local&&!s.player.camp&&!!c?.known&&c.terrain==='w'&&Math.abs(c.x-s.player.x)+Math.abs(c.y-s.player.y)===1;}
export function shoreSpec(s,c,owner={x:s.player.x,y:s.player.y}){const n=11,grid=Array.from({length:n},(_,y)=>Array.from({length:n},(_,x)=>!x||!y||x===10||y===10||x>=5?'#':'.'));grid[10][3]='E';return {id:`shore-${owner.x}-${owner.y}-${c.x}-${c.y}`,grid:grid.map(r=>r.join('')),containers:[{x:4,y:5,name:'岸边取水点',kind:'water'}],description:`${waterLabel(s,c)}岸边，陆地旁是不可步行的水面。靠近取水点可以收集污水。`};}
export function validateShore(s,id,m){const c=s.world.cells[`${m.shore?.x},${m.shore?.y}`],o=m.owner,land=s.world.cells[`${o?.x},${o?.y}`];if(m.kind!=='field'||!land||land.terrain==='w'||c?.terrain!=='w'||Math.abs(c.x-o.x)+Math.abs(c.y-o.y)!==1)throw Error('岸边归属无效');const spec=shoreSpec(s,c,o),objects=Object.values(m.containers);if(id!==spec.id||m.size!=='small'||JSON.stringify(m.grid)!==JSON.stringify(spec.grid)||m.portals?.length!==0||objects.length!==1||objects[0].x!==4||objects[0].y!==5||objects[0].kind!=='water'||objects[0].name!=='岸边取水点'||!objects[0].searched||Object.keys(objects[0].items).length||m.wildlife)throw Error('岸边布局无效');}
export const stomachLevel=s=>s.waterHealth?.until>s.time?s.waterHealth.severity:0;
export const waterRecovery=(s,minutes=1)=>1-.15*stomachLevel(s)*Math.min(minutes,Math.max(0,(s.waterHealth?.until??0)-s.time))/minutes;
export function advanceStomach(s,from){const w=s.waterHealth;if(!w)return;const elapsed=Math.max(0,Math.min(s.time,w.until)-from);s.stats.water=Math.max(0,s.stats.water-elapsed*.02*w.severity);if(w.severity===3)s.stats.health=Math.max(0,s.stats.health-elapsed*.015);if(w.until<=s.time){w.severity=0;w.until=0;}}
const hash=value=>{let n=2166136261;for(const c of String(value))n=Math.imul(n^c.charCodeAt(0),16777619);return (n>>>0).toString(36);};
export const waterWeather=(s,t)=>['晴','多云','小雨','多云'][parseInt(hash(s.seed+Math.floor(t/240)),36)%4];
export function rainCovered(l,o){return tiles(o).some(p=>l.objects.some(a=>a.type==='roof'&&a.x===p.x&&a.y===p.y));}
export function settleRain(s,from=s.time){for(const c of Object.values(s.world.cells)){const l=c.camp?.layout;if(!l)continue;for(const o of l.objects.filter(a=>a.type==='rainCollector')){let t=o.rainAt??from;o.rain??=0;if(!rainCovered(l,o))while(t<s.time&&o.rain<300){const end=Math.min(s.time,(Math.floor(t/240)+1)*240);if(waterWeather(s,t)==='小雨')o.rain=Math.min(300,o.rain+end-t);t=end;}o.rainAt=s.time;}}}
export function validateWater(s){for(const c of Object.values(s.world.cells)){const f=c.fishing;if(f!==undefined&&(!f||c.terrain!=='w'||!Number.isSafeInteger(f.bucket)||f.bucket<0||f.bucket>Math.floor(s.time/720)||!Number.isInteger(f.catches)||f.catches<0||f.catches>3))throw Error('钓鱼记录无效');}const w=s.waterHealth;if(w&&(!Number.isSafeInteger(w.drinks)||w.drinks<0||w.drinks>1e9||!Number.isInteger(w.severity)||w.severity<0||w.severity>3||!Number.isSafeInteger(w.until)||w.until<0||w.until>s.time+1440))throw Error('肠胃状态无效');if(s.waterHealth!==undefined&&!w)throw Error('肠胃状态无效');for(const c of Object.values(s.world.cells))for(const o of c.camp?.layout?.objects??[])if(o.type==='rainCollector'&&(!Number.isInteger(o.rain)||o.rain<0||o.rain>300||!Number.isSafeInteger(o.rainAt)||o.rainAt<0||o.rainAt>s.time))throw Error('雨水收集器记录无效');}

export const fishingLeft=(s,c)=>c?.fishing?.bucket===Math.floor(s.time/720)?3-c.fishing.catches:3;
