import {stancePanel} from './equipment-view.js';
import {weapon,cuttingTool,bowChance} from './equipment-data.js';
import {knownWildlife,SPECIES,BEHAVIORS} from './wildlife.js';
import {formatTime,localMap,approachPath,routeMinutes} from './engine.js';
import {RETALIATION,SCARE_CHANCE,corpseAge,corpseFreshness} from './hunting-data.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function wildlifePanel(s){const known=knownWildlife(s);return `<section class="fs-wildlife-panel"><small class="fs-kicker">WILDLIFE</small><h3>附近生物</h3>${stancePanel(s)}<p class="fs-muted">只显示当前可见个体；观察会推进游戏时间。</p><div class="fs-object-list">${known.visible.map(a=>`<button type="button" data-action="select" data-x="${a.x}" data-y="${a.y}"><b>${a.name}</b><small>${a.state} · ${a.x},${a.y}</small></button><small>${a.alive?`常态 ${a.speed} 格/分钟 · 奔跑 ${a.run} 格/分钟`:'尸体 · 点击检查与处理'}</small>`).join('')||'<p>视野内暂未发现生物。</p>'}</div><button type="button" data-action="observeWildlife">安静观察 · 5 分钟</button>${known.tracks.length?`<details><summary>附近踪迹 · ${known.tracks.length}</summary>${known.tracks.slice(-6).map(t=>`<p>${t.name}${t.type==='remains'?'捕食残迹':'足迹'} · ${t.x},${t.y}<br><small>${formatTime(t.time)}留下</small></p>`).join('')}</details>`:''}${known.memory.length?`<details><summary>历史观察 · 去向未确认</summary>${known.memory.map(o=>`<p>${esc(SPECIES[o.species].name)} · 当时${BEHAVIORS[o.state]}<br><small>${formatTime(o.time)} · 最后位置 ${o.x},${o.y}</small></p>`).join('')}</details>`:''}<p class="fs-muted">点击动物或尸体后查看操作。靠近时目标可能逃走；攻击或驱赶失败可能遭到反击。</p></section>`;}

export function regionWildlifePanel(s,c){const seen=Object.values(s.locals).filter(m=>m.owner?.x===c.x&&m.owner?.y===c.y&&m.wildlife).flatMap(m=>m.wildlife.observations).filter(o=>s.time-o.time<=1440).sort((a,b)=>b.time-a.time).slice(0,6);return seen.length?`<details><summary>生物观察记录 · 去向未确认</summary>${seen.map(o=>`<p>${SPECIES[o.species].name} · 当时${BEHAVIORS[o.state]}<br><small>${formatTime(o.time)}</small></p>`).join('')}</details>`:'';}

export function wildlifeActions(s,id){
 const a=localMap(s)?.wildlife?.animals.find(a=>a.id===id);if(!a)return '';const p=s.player.local,d=Math.abs(p.x-a.x)+Math.abs(p.y-a.y),tool=cuttingTool(s),w=weapon(s),alive=a.hp>0,checked=a.examinedAt!==undefined,path=d>1?approachPath(s,a.x,a.y):null;
 const button=(action,label,disabled=false)=>`<button type="button" data-action="${action}" data-actor="${esc(a.id)}" ${disabled||s.ended?'disabled':''}>${label}</button>`;
 return `<section class="fs-animal-actions"><h3>${alive?'与动物互动':'处理遗骸'}</h3><p>${alive?(a.hp<SPECIES[a.species].hp?'能看见伤势。':'未见明显伤势。'):`${corpseFreshness(s,a)} · ${checked?`可用生肉 ${corpseAge(s,a)<720?a.meat:0}、皮料 ${a.hide??0}`:'先检查剩余资源。'}`}</p><div class="fs-action-list">${d>1?button('approachAnimal',path?.length?`走近目标 · ${routeMinutes(s,path)} 分钟`:'尚无已知接近路线',!path?.length):''}${button('inspectAnimal','检查 · 1 分钟',d>1)}${alive?button('scareAnimal','驱赶 · 1 分钟 / 3 体力',d>3||s.stats.stamina<3)+(w.id==='bow'?button('shootAnimal',`射击 · 1 分钟 / 4 体力 / 3 伤害 · 命中 ${Math.round(bowChance(s,d)*100)}%`,d>w.range||!s.bag.arrow||s.stats.stamina<4):button('attackAnimal',`${w.name}攻击 · 1 分钟 / 6 体力 / ${w.damage} 伤害`,d>w.range||s.stats.stamina<6)):button('butcherAnimal','割取一份生肉 · 5 分钟 / 2 体力',d>1||!checked||!tool||s.stats.stamina<2||!a.meat||corpseAge(s,a)+5>=720)+button('skinAnimal','剥取一份皮料 · 8 分钟 / 2 体力',d>1||!checked||!tool||s.stats.stamina<2||!a.hide||corpseAge(s,a)+8>=1440)+button('clearAnimal','清理遗骸并丢弃剩余物资 · 3 分钟 / 1 体力',d>1||s.stats.stamina<1)}</div><p class="fs-muted">${alive?`驱赶需三格内，成功率 ${Math.round(SCARE_CHANCE[a.species]*100)}%；矛可攻击两格内，弓射程六格；均需当前可见。相邻攻击未击杀时有 50% 概率遭到 ${RETALIATION[a.species]} 点反击；相邻驱赶失败也会反击。武器需在背包装备；弓每次消耗一支箭，暂不可回收。`:'分割与剥皮需要工具。死亡 12 小时后不能取肉，24 小时后尸体消失；捕食动物会吃掉同一份肉。加工期间周围动物继续活动。'}</p></section>`;
}
