import {worn} from './durable-data.js';
import {ITEMS} from './engine.js';
import {campAt,canUseCampObject} from './camp-data.js';
import {WORKSHOP_RECIPES,UPGRADE_COSTS,benchLevel,usableBench,workshopError} from './workshop-data.js';
import {thermalSnapshot,heaterFuel,heaterHeat} from './temperature.js';
import {hasFacility} from './shelter-data.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(a,label,disabled=false,extra='')=>`<button type="button" data-action="${a}" ${disabled?'disabled':''} ${extra}>${label}</button>`;
const cost=(s,r)=>Object.entries(r).map(([id,n])=>`${ITEMS[id].name} ${s.bag[id]??0}/${n}`).join(' · ');
const lacks=(s,r)=>Object.entries(r).some(([id,n])=>(s.bag[id]??0)<n);
export function temperaturePanel(s){const t=thermalSnapshot(s),q=s.thermal??{wet:0,cold:0,heat:0};return `<section class="fs-survival-panel"><h3>温度与衣物</h3><p>室外 ${t.outdoor.toFixed(1)}℃ · 所在位置 ${t.temperature.toFixed(1)}℃ · ${t.label}</p><p>淋湿 ${Math.round(q.wet)}% · 受冷 ${Math.round(q.cold)}/100 · 过热 ${Math.round(q.heat)}/100</p><p>${t.heated&&t.temperature>=18&&t.temperature<=26&&q.wet<20?'温暖舒适：每小时精神 +1。':'完整房间可保温，但不会凭空升温；暖炉燃烧才能供暖。'}${q.cold>=80||q.heat>=80?'严重冷暖暴露正在损害健康。':''}</p>${button('wearCoat',worn(s).torso==='warmcoat'?'脱下保暖外套':'穿上保暖外套',!s.bag.warmcoat||s.ended)}<small>外套在低温下提供 +8℃ 等效保暖；淋湿最多抵消 4℃。穿脱不耗时，穿着的最后一件外套不能存入箱子。温度为简化游戏模型。</small></section>`;}
export function temperatureSummary(s){const t=thermalSnapshot(s),q=s.thermal;return `<span>环境 ${t.temperature.toFixed(1)}℃</span>${q?.wet>=20?`<span>淋湿 ${Math.round(q.wet)}%</span>`:''}${q?.cold>=25?`<span>${q.cold>=80?'严重失温':q.cold>=40?'受冷':'偏冷'}</span>`:''}${q?.heat>=25?'<span>过热</span>':''}${t.heated&&t.temperature>=18&&t.temperature<=26&&(q?.wet??0)<20?'<span class="fs-benefit-tag">温暖舒适</span>':''}`;}
export function workshopPanel(s){return `<section class="fs-survival-panel"><h3>工作台 · 材料加工</h3><p>旧工作台视为 1 级。升级解锁新设施与加工；地图模式需靠近所需工作台，简易模式可直接使用。材料从背包扣除。</p>${Object.entries(WORKSHOP_RECIPES).map(([id,r])=>`<details><summary>${r.name} · ${r.minutes} 分钟</summary><p>${r.level} 级工作台${r.metal?'＋金属工作台':''}<br>${cost(s,r.cost)} → ${Object.entries(r.output).map(([i,q])=>`${ITEMS[i].name} ${q}`).join('、')}</p>${button('workshopCraft','确认加工',s.ended||!usableBench(s,r.level)||r.metal&&!hasFacility(s,'metalbench')||lacks(s,r.cost),`data-recipe="${id}"`)}</details>`).join('')}<p>基础建材：木材、石料、布料、金属零件；加工材料：通用组件、机械零件、电子元件；生活用品：书籍、外套、燃料、电池。高级设施的解锁条件在布置面板显示。</p></section>`;}
export function furnitureFunctionPanel(s,o){if(!o)return '';const can=canUseCampObject(s,o)&&!s.ended,attr=`data-id="${o.id}"`;if(o.type==='bench'){const level=benchLevel(o),r=UPGRADE_COSTS[level+1];return `<section class="fs-survival-panel"><h3>工作台 ${level} / 3 级</h3><p>1 级：暖炉、金属工作台、椅子；2 级：扶手椅、书架、电子元件；3 级：收音机。升级不改变位置与原有制作功能。</p>${r?`<p>${cost(s,r)} · ${60*(level+1)} 分钟</p>${button('upgradeBench',`升级到 ${level+1} 级`,!can||lacks(s,r),`${attr} data-level="${level+1}"`)}`:'<p>已达到最高等级。</p>'}</section>${workshopPanel(s)}`;}if(o.type==='metalbench')return workshopPanel(s);if(o.type==='heater')return `<section class="fs-survival-panel"><h3>暖炉</h3><p>${o.heater?.lit?'燃烧中':'已关闭'} · 剩余燃料 ${heaterFuel(o,s.time)} 分钟</p><p>燃料 1 = 60 分钟，最多 480 分钟。完整小房间更易升温；面积越大，同一台暖炉的效果越弱。门打开后保温降低。燃料与余热随游戏时间消耗。</p>${button('heaterFeed','添加燃料 1 · 不耗时',!can||!s.bag.fuel||heaterFuel(o,s.time)>420,attr)}${button('heaterToggle',o.heater?.lit?'关闭暖炉':'点燃暖炉',!can||!o.heater?.lit&&!heaterFuel(o,s.time),attr)}</section>${temperaturePanel(s)}`;if(['chair','armchair','bookshelf','radio'].includes(o.type)){const wait=Math.max(0,(s.relaxUntil??0)-s.time);return `<section class="fs-survival-panel"><h3>${esc(o.name)} · 休闲</h3><p>休闲 30 分钟，体力 +5，精神 +${{chair:3,armchair:5,bookshelf:8,radio:8}[o.type]}。${o.type==='bookshelf'?'需要携带书籍，不消耗。':o.type==='radio'?'每次消耗电池 1；本版仅播放广播休闲，不生成线索。':''}所有休闲家具共享 3 小时间隔。</p>${wait?`<p>还需等待 ${wait} 分钟。</p>`:''}${button('relaxFurniture','开始休闲 · 30 分钟',!can||wait>0||o.type==='bookshelf'&&!s.bag.book||o.type==='radio'&&!s.bag.battery,attr)}</section>`;}return '';}
export const unlockNote=(s,type)=>{const e=workshopError(s,type);return e?`<p class="fs-muted">${e}</p>`:'';};
